### ISSUE TITLE
While doing image comparison in the workflows, red boxes are coming Is there any way to avoid that?

### ISSUE THREAD

**Issue by Truculent1997** [healenium/healenium-web#105]

**Comment by GannaChernyshova** [comment]
Hi @Truculent1997 
fix is already in-progress

**Comment by Truculent1997** [comment]
When these changes will push to the maven repository?

**Comment by Aliaksei-Ashukha** [comment]
Hello @Truculent1997 
Fixed in 3.1.3 version. Please check.
Note: Use 'backlight-healing = true' flag in properties to manage behavior
