### ISSUE TITLE
Unable to heal the in all versions (3.0.2,3.0.9,3.1)

### ISSUE THREAD

**Issue by nareshm1** [healenium/healenium-web#110]
@GannaChernyshova @Aliaksei-Ashukha When trying to start the hlm-backend:latest or 3.1 is throwing error as some liquidbase file missing and container exits in seconds

**Comment by Aliaksei-Ashukha** [comment]
Hi @nareshm1, Do you up docker container or run application local ?  Could you attach the full error or stacktrace ?

**Comment by nareshm1** [comment]
@GannaChernyshova @Aliaksei-Ashukha I have followed below steps :

1.Created a pom project with maven
2. imported dependency for 3.1
3. up the docker 



4. ran the script with healing is true in healenium.prop file 
5.No changes on html and ran perfectly 
6.Now changed the html element with minute change 
7 .Now ran the mvn test
8. Occurs below error

**Comment by Aliaksei-Ashukha** [comment]
Hi @nareshm1 
Please, use 3.1.1 version of healenium-web and healenium-backend services.

**Comment by nareshm1** [comment]
@Aliaksei-Ashukha I have tried with 3.1.1 version vut still facing the brlow issues
![PicsArt_07-28-12.42.02.jpg](https://user-images.githubusercontent.com/67036539/127213834-03ba5f53-f167-4f07-b73e-b309edcb3f8c.jpg)
![PicsArt_07-28-12.41.49.jpg](https://user-images.githubusercontent.com/67036539/127213874-2a032b7e-fabf-482e-baab-1ee3e5f5e280.jpg)![PicsArt_07-28-12.41.35.jpg](https://user-images.githubusercontent.com/67036539/127213894-dcf93cdb-93b4-4534-be90-f8435af14294.jpg)

**Comment by Aliaksei-Ashukha** [comment]
Hello @nareshm1 
As I can see the issue in your test method and Jsoup. 
Healenium it's got nothing to do
