### ISSUE TITLE
Does healenium 3.x version works without the integration of hlm-backend and db like how it used to work for healenium-2.0.5?

### ISSUE THREAD

**Issue by KarthikaRavichandran** [healenium/healenium-web#114]
Hi,

Can I please know if healenium 3.x version works without the integration of hlm-backend and db like how it used to work for healenium-2.0.5?

Also, is healenium-2.x depricated?

Any response on this is much helpful as I have fully integrated 2.x in my live project.

Thank you.

**Comment by Aliaksei-Ashukha** [comment]
Hi @KarthikaRavichandran 
You are right, 2.x is deprecated. Please, use 3.1+  version.
3.x- doesn't work without the integration of hlm-backend and db. Use docker-compose to up both containers.
