### ISSUE TITLE
Unable to self heal in selenium Maven Java

### ISSUE THREAD

**Issue by saranmani** [healenium/healenium-web#117]
Hi,
I have tried implementing self heal with selenium maven java project to locate the newly changed locators in the web page.
I tried the same from the below link 
**_https://www.linkedin.com/pulse/self-healing-selenium-healenium-opensource-test-solution-murari/?trackingId=%2BOluy%2FdcQBeftZ2sDSC2XA%3D%3D_**
My docker is running and container status is up. My first time test case is getting passed. When i change the xpath and run for the second time, it is not able to identify the new locator. I have provided the necessary snapshots . Kindly help me on the issue
<img width="960" alt="dom" src="https://user-images.githubusercontent.com/12432584/124915551-4c0d3f80-e00f-11eb-9d32-644f057a6ccf.png">
<img width="960" alt="xpath in code" src="https://user-images.githubusercontent.com/12432584/124915587-54657a80-e00f-11eb-919c-1333fc708709.png">
<img width="960" alt="Containerstatus" src="https://user-images.githubusercontent.com/12432584/124915597-57606b00-e00f-11eb-97cd-5ed865afc15c.png">
<img width="960" alt="errorscreenshot" src="https://user-images.githubusercontent.com/12432584/124915601-58919800-e00f-11eb-822c-13bf12f82160.png">

**Comment by Aliaksei-Ashukha** [comment]
Hello @saranmani ,
Nice to meet you

It looks strongly. Try to decrease value of score-cap

**Comment by saranmani** [comment]
The issue is resolved after updating the healenium-web dependency with 3.1 version
