### ISSUE TITLE
WARNING: A connection to "Backend URL" was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

### ISSUE THREAD

**Issue by Truculent1997** [healenium/healenium-web#118]
This warning starts coming halfway through the workflow. It keeps on coming till the end

**Comment by KritikaSahare1611** [comment]
@Aliaksei-Ashukha I am also getting the same issue,

Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
com.epam.healenium.client.RestClient - Failed to make response
java.net.SocketTimeoutException: timeout

**Comment by Aliaksei-Ashukha** [comment]
Fixed at rev. 3.2.0
