### ISSUE TITLE
failed to make response error

### ISSUE THREAD

**Issue by sathya2388** [healenium/healenium-web#125]
Hi , we have configured hlm-backend & Postgres and it is running in the backend. But when we run the maven project getting an error like failed to make response error. Can some one please help us on this issue. 

we have configured hlm-backend in linux server with port 7878 & postgres with port 5433. PLease refer the attached files for more details. [](url)
![Console error](https://user-images.githubusercontent.com/56147458/127482816-2301dfed-4fe8-4556-bf08-79bdd1cc8339.PNG)
![Folder Structure](https://user-images.githubusercontent.com/56147458/127482820-32f370f6-f399-4807-ae4f-c2f3a11c8386.png)
![Test Demo](https://user-images.githubusercontent.com/56147458/127482821-a7f87283-c8e1-4f29-8c8f-fb972df95adc.png)

**Comment by sathya2388** [comment]
can someone please let us know if we are  missing something.

**Comment by Aliaksei-Ashukha** [comment]
Hi @sathya2388,
Are you sure that you specify host of Linux server in properties file?

**Comment by sathya2388** [comment]
Hi.
yes now this issue is fixed due to properties file. However we are getting no such element error . DO you have sometime to connect through skype. We are not sure what are we missing. 

OR can you pls give the steps to verify it 
![image](https://user-images.githubusercontent.com/56147458/129018686-5d29375e-93b4-4194-8783-6409ce674829.png)

**Comment by sathya2388** [comment]
Sorry I could not connect yesterday.. when can we connect?

**Comment by sathya2388** [comment]
Thanks. It's working now. Hence closing this ticket
