### ISSUE TITLE
 port 8000 is hard coded in rest client

### ISSUE THREAD

**Issue by Zarkonan** [healenium/healenium-web#128]
Fixed port in rest client. i update code at my local to  config.getInt("serverPort") and its working      
baseUrl = "http://" + config.getString("serverHost") + ":" + config.getInt("serverPort") + "/healenium";
        imitateUrl = "http://" + config.getString("serverHost") + ":" + **"8000"** + "/imitate";

mean to say port 8000 is hard coded

**Comment by Aliaksei-Ashukha** [comment]
It fixed in 3.1.4v
