### ISSUE TITLE
New element locators have not been found

### ISSUE THREAD

**Issue by naveenkmr2310** [healenium/healenium-web#132]
Hi Team,
We have integrated the backend and db using the latest version healenium 3.1.4. While changing the locator of the dom during runtime, we are experience a warning and healing is not happening.

Please find the below error message for your reference!!

-----------------------------------------------------------------------------------------------------------------------------------------
24775 [pool-2-thread-1] WARN com.epam.healenium.handlers.proxy.BaseHandler - Failed to find an element using locator By.xpath: //*[@id="twotabsearchtextbox"]
Reason: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="twotabsearchtextbox"]"}
  (Session info: chrome=92.0.4515.131)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'S1660L', ip: '10.245.24.69', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
Driver info: com.java.CustomRemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 92.0.4515.131, chrome: {chromedriverVersion: 91.0.4472.101 (af52a90bf870..., userDataDir: C:\Users\naveen.s\AppData\L...}, goog:chromeOptions: {debuggerAddress: localhost:56787}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: bc32285fc4eb25d57781831409a...}
Session ID: bc32285fc4eb25d57781831409af4793
*** Element info: {Using=xpath, value=//*[@id="twotabsearchtextbox"]}
Trying to heal...
25196 [pool-2-thread-1] WARN com.epam.healenium.service.impl.HealingServiceImpl - New element locators have not been found
25196 [pool-2-thread-1] WARN com.epam.healenium.service.impl.HealingServiceImpl - Score property=0.1 is bigger than healing's locator score
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by Aliaksei-Ashukha** [comment]
Hello @naveenkmr2310 ,
Did you run pure tests before do healing

**Comment by ElenaStepuro** [comment]
Closed because no answer and more details have been provided

**Comment by chethanmp-agi** [comment]
getiing error.. any suggestion plz 
com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.

**Comment by Aliaksei-Ashukha** [comment]
Hello @chethanmp-agi ,
"New element locator have not been found. There is a lack of reference data." means etalon data has not survived after pure tests.
Kindly check data appropriate locator in the "selector" table of postgres database.

**Comment by haribabusunkari** [comment]
[main] WARN com.epam.healenium.processor.FindElementProcessor - Failed to find an element using locator By.xpath: .//button[@id='u_0_5_VP']
Reason: no such element: Unable to locate element: {"method":"xpath","selector":".//button[@id='u_0_5_VP']"}
  (Session info: chrome=102.0.5005.61)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.0', revision: '87802e897b'
System info: host: 'DESKTOP-L911IRE', ip: '192.168.29.128', os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_351'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [374443f2de8fa189d78e5fcea7187060, findElement {using=xpath, value=.//button[@id='u_0_5_VP']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 102.0.5005.61, chrome: {chromedriverVersion: 102.0.5005.61 (0e59bcc00cc4..., userDataDir: /tmp/.com.google.Chrome.T4Val1}, goog:chromeOptions: {debuggerAddress: localhost:36327}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 374443f2de8fa189d78e5fcea7187060
**Trying to heal...**
[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.
org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":".//button[@id='u_0_5_VP']"}
  (Session info: chrome=102.0.5005.61)

Did setup as mentioned in docker-compose.yaml

Using Selenoid  - https://github.com/healenium/healenium

Healium-web = 3.2.5
selenium remotedriver - 4.1.0 
Verified postgres ... selector tables xpaths storing properly
![image](https://user-images.githubusercontent.com/7441923/199506479-ce2a73c1-5251-416b-9f5d-25da53aab206.png)

**Comment by Aliaksei-Ashukha** [comment]
Hi @haribabusunkari ,
As we see, there is no target locator {using=xpath, value=.//button[@id='u_0_5_VP']} in the database.
Kindly run success test to let healenium store it like etalon data.

**Comment by haribabusunkari** [comment]
working now thanks

**Comment by AkashSai10** [comment]
Hi,
Is there a way that I can verify the postgres by myself?
