### ISSUE TITLE
Unable to form locator with special characters

### ISSUE THREAD

**Issue by divya2021** [healenium/healenium-web#137]
the webelements attributes values contains special characters like ":", When healenium try to heal the elements with special characters like ":", it throws invalid selector and unable to heal the elements.

**Comment by Aliaksei-Ashukha** [comment]
Hello @divya2021 ,

Could you provide example such locator and logs? 

Thanks

**Comment by divya2021** [comment]
Hi, One of the element id contains attribute as "id="expertModeSubviewCompactView:expertModeForm:toggleMode"", it contains special characters as ":", when healing it throws the error message as invalid selector. because it usings attribute value for forming the css locator

**Comment by divya2021** [comment]
Also, to add a note here. The selector suggested by the healenium is "a#expertModeSubviewCompactView:expertModeForm:toggleMode", but it throws invalid selector. Because we need to use escape sequence to find the element like this "driver.findElement(By.cssSelector("a#expertModeSubviewCompactView\\:expertModeForm\\:toggleMode"));"

**Comment by ElenaStepuro** [comment]
Fixed
