### ISSUE TITLE
Self healing is working but healenium report is empty

### ISSUE THREAD

**Issue by jeet90** [healenium/healenium-web#138]
I have used healenium/hlm-backend:3.1.3 but reports are not getting generated.

**Comment by jeet90** [comment]
Below is the screenshot of the logs :- <img width="766" alt="Whatever" src="https://user-images.githubusercontent.com/20114220/133334212-53ebaf51-2318-4052-9cbd-31c8fbb84a67.PNG">

**Comment by ElenaStepuro** [comment]
Hi @jeet90 !
Please, use version _healenium/hlm-backend:3.1.2_
Also, I recommend to clean docker volumes.

**Comment by jeet90** [comment]
Working as expected now.
