### ISSUE TITLE
Explicit waiter doesn't work with healenium instanse

### ISSUE THREAD

**Issue by tantana1993** [healenium/healenium-web#139]
Please help me, when I instantiate WebDriverWait object using SelfHealingDriver instance it simply doesn't wait for an element to be visible on the page:
webDriver = new ChromeDriver();
selfHealingDriver = SelfHealingDriver.create(webDriver);
webDriverWait = new WebDriverWait(selfHealingDriver, 10);
webDriverWait .until(ExpectedConditions.visibilityOfElementLocated(By.xpath("someXPATH")));
I navigate to the page where the element should be located and right after that I get IndexOutOfBoundsException , and of course if I use WebDriver in WebDriverWait  constructor everything works fine

So the question is: couldn't we use WebDriverWait  with SelfHealingDriver instance in constructor?
And if we couldn't, then how can we solve this?

**Comment by Aliaksei-Ashukha** [comment]
Hello @tantana1993 
We'll check it in nearest future.
