### ISSUE TITLE
Getting java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/Locatable

### ISSUE THREAD

**Issue by sudiprai10** [healenium/healenium-web#150]
HI,
Can you please helping in understand why I am getting below error when I integrated Healenium with in framework. Please refer the screenshot.

![image](https://user-images.githubusercontent.com/25118438/137082758-0cb36699-3562-4eb8-ae86-5af74da93ade.png)

**Comment by sudiprai10** [comment]
> Hello @sudiprai10 ! Could you please provide more information?) Which healenium web and backend version do you use? Is this issue reproduced for all locators or for some specific?

Hi @ElenaStepuro  healenium web version is 3.1.4. Yes issue is reproduced for all locators.

**Comment by sudiprai10** [comment]
> @sudiprai10 please, use selenium version 3.141.59 for all of these jars

@ElenaStepuro Thanks for your input. It is working now.

**Comment by Abhi01290** [comment]
I am getting the below error while trying to run the script

      java.lang.NoClassDefFoundError: org/openqa/selenium/support/locators/RelativeLocator$RelativeBy
	at com.epam.healenium.mapper.HealeniumMapper.<init>(HealeniumMapper.java:44)
	at com.epam.healenium.SelfHealingDriver.setEngineFields(SelfHealingDriver.java:55)
	at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:41)

I am using the following dependency version in POM.xml 
org.junit.jupiter:junit-jupiter-api: 5.9.3
org.junit.jupiter:junit-jupiter-engine: 5.9.3
org.seleniumhq.selenium:selenium-java: 3.141.59
io.github.bonigarcia:webdrivermanager: 5.4.1
healenium-web                                      : 3.4.3

And I am using the below code
	WebDriverManager.chromedriver().setup();
	WebDriver delegate = new ChromeDriver();
	driver= SelfHealingDriver.create(delegate);

Please provide the resolution..

**Comment by maysolan** [comment]
> I am getting the below error while trying to run the script
> 
> ```
>   java.lang.NoClassDefFoundError: org/openqa/selenium/support/locators/RelativeLocator$RelativeBy
> at com.epam.healenium.mapper.HealeniumMapper.<init>(HealeniumMapper.java:44)
> at com.epam.healenium.SelfHealingDriver.setEngineFields(SelfHealingDriver.java:55)
> at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:41)
> ```
> 
> I am using the following dependency version in POM.xml org.junit.jupiter:junit-jupiter-api: 5.9.3 org.junit.jupiter:junit-jupiter-engine: 5.9.3 org.seleniumhq.selenium:selenium-java: 3.141.59 io.github.bonigarcia:webdrivermanager: 5.4.1 healenium-web : 3.4.3
> 
> And I am using the below code WebDriverManager.chromedriver().setup(); WebDriver delegate = new ChromeDriver(); driver= SelfHealingDriver.create(delegate);
> 
> Please provide the resolution..

Did you receive any fix on this <init> element issue?

**Comment by umredkarabhijeet** [comment]
Hi, I am getting following error on this line :- 	

driver = SelfHealingDriver.create(delegate);

java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices
	at com.epam.healenium.utils.ProxyFactory.createDriverProxy(ProxyFactory.java:35)
	at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:45)
	at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:34)

my selenium version is 4.11.0 and healenium-web is 3.2.0. 
Could someone help to fix above exception?

**Comment by Abhi01290** [comment]
> > I am getting the below error while trying to run the script
> > ```
> >   java.lang.NoClassDefFoundError: org/openqa/selenium/support/locators/RelativeLocator$RelativeBy
> > at com.epam.healenium.mapper.HealeniumMapper.<init>(HealeniumMapper.java:44)
> > at com.epam.healenium.SelfHealingDriver.setEngineFields(SelfHealingDriver.java:55)
> > at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:41)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am using the following dependency version in POM.xml org.junit.jupiter:junit-jupiter-api: 5.9.3 org.junit.jupiter:junit-jupiter-engine: 5.9.3 org.seleniumhq.selenium:selenium-java: 3.141.59 io.github.bonigarcia:webdrivermanager: 5.4.1 healenium-web : 3.4.3
> > And I am using the below code WebDriverManager.chromedriver().setup(); WebDriver delegate = new ChromeDriver(); driver= SelfHealingDriver.create(delegate);
> > Please provide the resolution..
> 
> Did you receive any fix on this element issue?

> Yes, I resolved this error. First, you need to install Selenium version 4.0 or above, and then ensure you have the Maven plugin for Healenium. For a step-by-step guide, visit this site: https://healenium.io/docs/overview.

**Comment by Abhi01290** [comment]
> Hi, I am getting following error on this line :-
> 
> driver = SelfHealingDriver.create(delegate);
> 
> java.lang.NoClassDefFoundError: org/openqa/selenium/interactions/HasInputDevices at com.epam.healenium.utils.ProxyFactory.createDriverProxy(ProxyFactory.java:35) at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:45) at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:34)
> 
> my selenium version is 4.11.0 and healenium-web is 3.2.0. Could someone help to fix above exception?

Yes, I resolved this error. First, you need to install Selenium version 4.0 or above, and then ensure you have the Maven plugin for Healenium. For a step-by-step guide, visit this site: https://healenium.io/docs/overview.
