### ISSUE TITLE
Healing fails when there is a conditional wait to accept as Alert

### ISSUE THREAD

**Issue by mohitb01** [healenium/healenium-web#151]
Hi @GannaChernyshova @DzmitryHumianiuk @Aliaksei-Ashukha 

When using Healenium driver not able to accept alert.

**WebDriverWait wait = new WebDriverWait(driver, Timeout);
wait.until(ExpectedConditions.alertIsPresent());**

Above code returns **false** all time even if Alert is present. Can anyone please look into this issue.

Thanks,

**Comment by Aliaksei-Ashukha** [comment]
Hi @mohitb01 
Fixed at rev. 3.1.7

**Comment by mohitb01** [comment]
Thanks @Aliaksei-Ashukha Its working now.
