### ISSUE TITLE
java.io.IOException: unexpected end of stream on Connection{localhost:7878, proxy=DIRECT hostAddress=localhost/0:0:0:0:0:0:0:1:7878 cipherSuite=none protocol=http/1.1}

### ISSUE THREAD

**Issue by swnathan** [healenium/healenium-web#153]
Getting below exception in backend

org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108)\n at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)\n at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)\n at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)\n at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)\n at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)\n at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)\n at com.epam.healenium.Application.main(Application.java:9)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)\n at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)\n at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)\n Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT DATABASECHANGELOGLOCK_PKEY PRIMARY KEY (ID))]\n at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:295)\n at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:213)\n at liquibase.Liquibase.update(Liquibase.java:184)\n at liquibase.Liquibase.update(Liquibase.java:179)\n at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:366)\n at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:314)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1862)\n at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1799)\n ... 26 common frames omitted\n Caused by: liquibase.exception.DatabaseException: ERROR: no schema has been selected to create in\n Position: 14 [Failed SQL: (0) CREATE TABLE databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT DATABASECHANGELOGLOCK_PKEY PRIMARY KEY (ID))]\n at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402)\n at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)\n at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)\n at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:111)\n at liquibase.lockservice.StandardLockService.init(StandardLockService.java:102)\n at liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:252)\n ... 33 common frames omitted\n Caused by: org.postgresql.util.PSQLException: ERROR: no schema has been selected to create in\n Position: 14\n at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)\n at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)\n at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)\n at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)\n at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)\n at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:311)\n at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:297)\n at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:274)\n at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:269)\n at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)\n at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)\n at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398)\n ... 38 common frames omitted\n

**Comment by Aliaksei-Ashukha** [comment]
Hi @swnathan 
Please, use web 3.1.6v

**Comment by ElenaStepuro** [comment]
Closed because no updates
