### ISSUE TITLE
[BUG] Select class of selenium not working with healenium driver.

### ISSUE THREAD

**Issue by mohitb01** [healenium/healenium-web#158]
Hi @Aliaksei-Ashukha ,

I am trying to select a value from a dropdown using index. When I use simple selenium driver it works fine but when I use healenium driver its not able to select the value. There is no error as such but value is not selected on the application.
**NOTE** : I also used selectByValue too, its also not working.

**Browser** : IE
Healenium version : 3.1.7

**Code snippet** 
Select sel = new Select(WebElement we);
sel.selectByIndex(1);   or sel.selectByValue("Testing");

Thanks,

**Comment by ElenaStepuro** [comment]
Hello @mohitb01 !
Both this methods are using findElements method. I've described you details about it here: https://github.com/healenium/healenium-web/issues/159
So, you've described two different situations but issue is the same

**Comment by ElenaStepuro** [comment]
Fixed in hlm-web version [3.2.0](https://search.maven.org/search?q=g:%22com.epam.healenium%22%20AND%20a:%22healenium-web%22)
