### ISSUE TITLE
When using findElements() method for retrieving table elements using healenium driver it take around 25 mins.

### ISSUE THREAD

**Issue by mohitb01** [healenium/healenium-web#159]
Hi,
Scenario : I want to traverse a table and get all elements. I am using findElements(xpath) method to traverse through the table. There are around 156 elements in the table. 
Now when I use healenium driver to do the task it take around 20 mins to execute till the time my application logouts. With simple driver it works fine.

**Healenium version : 3.1.7**
Code **List<WebElement> table = driver.findElements(xpath);**

Can anyone please look into this.

Thanks,

**Comment by ElenaStepuro** [comment]
Hello @mohitb01 !
This is a know issue with findElements method.
We'll notify you about some updates

**Comment by KritikaSahare1611** [comment]
@ElenaStepuro Is this issue fixed ?

**Comment by ElenaStepuro** [comment]
Hello @KritikaSahare1611 ! We work on it in current release which will finish at the end of this year

**Comment by ElenaStepuro** [comment]
Fixed in hlm-web version [3.2.0](https://search.maven.org/search?q=g:%22com.epam.healenium%22%20AND%20a:%22healenium-web%22)
