### ISSUE TITLE
[Need support]: need sample for parallel test with healenium

### ISSUE THREAD

**Issue by veeramanikandanvv** [healenium/healenium-web#164]
### Describe the problem

Can someone help us in providing a sample usage of healenium for parallel test in java

### Healenium Web version

Latest

### Healenium Backend version

Latest

### Selenium version

4

### Platform

Java

### Logs appeared during using Healenium

```shell
Na
```

### Additional context

Driver cast issue

**Comment by ElenaStepuro** [comment]
Hello @veeramanikandanvv !
There are no special steps to run tests in parallel with Healenium. They are running in the same way as usually.
