### ISSUE TITLE
Healenium javascripts support

### ISSUE THREAD

**Issue by PavanDuvvuri** [healenium/healenium-web#167]
Does Healenium supports javascripts with WebdriverIO tool?

**Comment by ElenaStepuro** [comment]
Hello @PavanDuvvuri !
Yes, Healenium supports javascript language. The steps to use it are the same as for Python and .NET platforms. Please, find examples here: https://github.com/healenium/healenium-example-python

**Comment by PavanDuvvuri** [comment]
Hello @ElenaStepuro  Thanks for your reply. I'm able to execute dot net version by making all other containers up and running in local..I think the same remote webdriver of selenium I need to use for javascript automation as well by referring from these https://github.com/healenium/healenium-example-dotnet  templates..

**Comment by ElenaStepuro** [comment]
Hello @PavanDuvvuri , correct, you can use dotnet templates. And one small thing which is not mentioned there: WebDriver creation differ from Java usage. You don't need to create SelfHealingDriver; instead of it to use Healenium you should create RemoteWebDriver by URL http://<your host>:8085

**Comment by PavanDuvvuri** [comment]
Thanks @ElenaStepuro, do you have any sample script on how to invoke driver using RemoteWebDriver at "http://localhost:8085" in javascript? I m using wedriverIO tool..
thanks

**Comment by PavanDuvvuri** [comment]
HI @ElenaStepuro I followed https://webdriver.io/docs/configurationfile/ and it worked, thanks
