### ISSUE TITLE
I am not able to proceed further after detecting the locator 

### ISSUE THREAD

**Issue by priyanka748** [healenium/healenium-web#172]
### Describe the problem

In my code.. 

If i send keys in the text box.. after that it is getting clicked.. but not proceeding further. ie not navigating to the next page
here first code of line is getting executed, even second too but m not able to see the automation page.. which is not the case whn i run normally without any changing the xpath or name in test browser
<img width="400" alt="Cape" src="https://user-images.githubusercontent.com/49894816/152142028-642fcf2b-8d0e-46b3-9607-d5baf2f63d61.PNG">
<img width="461" alt="Cture" src="https://user-images.githubusercontent.com/49894816/152142058-d314861c-6786-4e9a-b381-cf1c33289462.PNG">

### Healenium Web version

healenium-web 3.2.1

### Healenium Backend version

 healenium-back version 3.2.0

### Selenium version

4.1.1

### Platform

Java

### Logs appeared during using Healenium

```shell
Session ID: 049c792824779e9c3f5e9501fb46e60a
Trying to heal...
[main] WARN com.epam.healenium.processor.SaveHealingResultsProcessor - Using healed locator: Scored(score=0.9880252100840337, value=By.cssSelector: input.gLFyf.gsfi)
```

**Comment by ElenaStepuro** [comment]
Hello @priyanka748 could you please describe test steps and what do you expect?

**Comment by priyanka748** [comment]
1) Launch the browser
2) go to www.google.com
3) enter automation with the healing on
4) click on search 

Here , till 3rd step everything is working fine.. the locator is found by healenium.. But whn it press click after that.. then automation getting removed and return nothing.. a empty text box

**Comment by priyanka748** [comment]
Can you plzz mention which settings I have to check?

**Comment by priyanka748** [comment]
nd are you able to get into next page. 
![image](https://user-images.githubusercontent.com/49894816/152202470-0f1440fb-5101-4826-983f-6a7ef5b9fa95.png)

**Comment by priyanka748** [comment]
Version 97.0.4692.99 This chrome browser m using

**Comment by ElenaStepuro** [comment]
@priyanka748 I think you can read this article: https://support.google.com/chrome/thread/10251942/blank-page-from-google-search-but-page-context-is-still-clickable?hl=en
Looks like in your example)

However, this is not healenium issue. In this case, I'll close the issue

**Comment by priyanka748** [comment]
Thanks @ElenaStepuro
