### ISSUE TITLE
[Need support]: 

### ISSUE THREAD

**Issue by MeenakshiTomar** [healenium/healenium-web#174]
### Describe the problem

I am facing issues while generating healenium report as no data is getting seeded in healnium.report table, though the element is getting healed and entries are getting created in healenium.healing_result and healenium.healing table for the healed locator in that session.
With the session ID which is getting created in console, when the driver is getting invoked is generating empty report on link
http://10.131.141.181:7878/healenium/report/8d161f3fd971c9c2023b0f4e63602274.

I have added hlm-report dependency in gradle file of version 1.1 and healenium-web version 3.1.7

repositories {
	maven{
		url "https://plugins.gradle.org/m2/"
		}
	}

dependencies {   
compile group: 'com.epam.healenium', name: 'healenium-web', version: '3.1.7'
compile group: 'com.epam.healenium', name: 'hlm-report', version: '1.1' 
}

and then I am running my tests via TESTNG
and the below mentioned session id is what I am getting in console
**Session ID: 886fcd735a52c42fa57ffbed4dd409d0
*** Element info: {Using=name, value=callback_2}
Trying to heal...
2022-02-15 17:02:46 WARN  AbstractHealingServiceImpl:83 - Using healed locator: Optional[Scored(score=0.9862857142857142, value=By.name: healLogin)]
2022-02-15 17:02:48 INFO  BasicPageElementHelper:58 - findElementByClickable: [ By.name: callback_2 ] with timeout: 180**

### Healenium Web version

3.1.7

### Healenium Backend version

3.1.5

### Platform

java

### Logs appeared during using Healenium

```shell
Session ID: 886fcd735a52c42fa57ffbed4dd409d0
*** Element info: {Using=name, value=callback_2}
Trying to heal...
2022-02-15 17:02:46 WARN  AbstractHealingServiceImpl:83 - Using healed locator: Optional[Scored(score=0.9862857142857142, value=By.name: healLogin)]
2022-02-15 17:02:48 INFO  BasicPageElementHelper:58 - findElementByClickable: [ By.name: callback_2 ] with timeout: 180
```

**Comment by MeenakshiTomar** [comment]
@ElenaStepuro @GannaChernyshova Please help as I have to present the solution to the Leads because they are willing to use healenium in our organisation.

**Comment by ElenaStepuro** [comment]
@MeenakshiTomar how do you run your tests? Please, try to run them via gradle comand

**Comment by Aliaksei-Ashukha** [comment]
Hi @MeenakshiTomar as we can see, you check http://10.131.141.181:7878/healenium/report/8d161f3fd971c9c2023b0f4e63602274 report with applied for different test execution session.
Note: after each test run created new report with different url
