### ISSUE TITLE
[BUG]: No tests are run after upgrading to healenium-web 3.2.3

### ISSUE THREAD

**Issue by MohabMohie** [healenium/healenium-web#177]
### Describe the bug

After upgrading the dependency in my automation engine, no tests are executed from the mvn command line.
Tests run normally via the IDE (latest IntelliJ) but not via the command line.

Investigation shows that several dependencies were added and upgraded to the latest healenium-web, and though I have no conflicts in the pom.xml dependency tree, but it seems that one of them have messed up something discreetly.

Note how the execution time was over 15 minutes before the upgrade to version 3.2.3, and was reduced to 2 minutes (because no tests are run)
![image](https://user-images.githubusercontent.com/19201898/158177920-825a9019-7c82-43ef-aa06-27896ba4dda2.png)

Console logs with version 3.2.3 running a simple `mvn clean test -Dtest=Test_google` command are below in the logs section.

Console logs running the same command after downgrading to version 3.22 are below in the expected behavior section.

### How to reproduce the issue

```shell
the problem appears when I run using mvn commandline, but reqular ee
```

### Logs appeared during using Healenium

```shell
C:\Users\Mohab\.jdks\openjdk-17.0.2\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE -Dmaven.home=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3 -Dclassworlds.conf=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven-event-listener.jar -javaagent:D:\ideaIC-2020.3.2.win\lib\idea_rt.jar=57344:D:\ideaIC-2020.3.2.win\bin -Dfile.encoding=UTF-8 -classpath D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.2 clean test -Dtest=Test_google
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< io.github.mohabmohie:SHAFT_ENGINE >------------------
[INFO] Building io.github.mohabmohie:SHAFT_ENGINE 6.1.20220313
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SHAFT_ENGINE ---
[INFO] Deleting C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ SHAFT_ENGINE ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 43 resources to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE/target/classes/resources
[INFO] Copying 8 resources to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\site
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ SHAFT_ENGINE ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 66 source files to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\classes
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/main/java/com/shaft/gui/element/TouchActions.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/main/java/com/shaft/gui/element/TouchActions.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- hlm-report-mvn:1.1:initReport (hlmReport) @ SHAFT_ENGINE ---
[INFO] Healenium server Port = 7878
[INFO] Healenium server Host = localhost
Mar 14, 2022 3:05:53 PM com.epam.healenium.client.HealingClient makePost
WARNING: Failed to perform POST request. Reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:7878
[INFO] sessionKey= null
[WARNING] Couldn't obtain session key from server!
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ SHAFT_ENGINE ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 18 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ SHAFT_ENGINE ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 55 source files to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\test-classes
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/testPackage01/appium/IOSBasicInteractionsTest.java: Some input files use or override a deprecated API.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/testPackage01/appium/IOSBasicInteractionsTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/poms/GoogleSearch.java: Some input files use or override a deprecated API that is marked for removal.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/poms/GoogleSearch.java: Recompile with -Xlint:removal for details.
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ SHAFT_ENGINE ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO]
```

### Expected behavior

`
C:\Users\Mohab\.jdks\openjdk-17.0.2\bin\java.exe -Dmaven.multiModuleProjectDirectory=C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE -Dmaven.home=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3 -Dclassworlds.conf=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\bin\m2.conf -Dmaven.ext.class.path=D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven-event-listener.jar -javaagent:D:\ideaIC-2020.3.2.win\lib\idea_rt.jar=57517:D:\ideaIC-2020.3.2.win\bin -Dfile.encoding=UTF-8 -classpath D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\boot\plexus-classworlds-2.6.0.jar;D:\ideaIC-2020.3.2.win\plugins\maven\lib\maven3\boot\plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.3.2 clean test -Dtest=Test_google
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< io.github.mohabmohie:SHAFT_ENGINE >------------------
[INFO] Building io.github.mohabmohie:SHAFT_ENGINE 6.1.20220313
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ SHAFT_ENGINE ---
[INFO] Deleting C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ SHAFT_ENGINE ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 43 resources to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE/target/classes/resources
[INFO] Copying 8 resources to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\site
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ SHAFT_ENGINE ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 66 source files to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\classes
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/main/java/com/shaft/gui/element/TouchActions.java: Some input files use unchecked or unsafe operations.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/main/java/com/shaft/gui/element/TouchActions.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- hlm-report-mvn:1.1:initReport (hlmReport) @ SHAFT_ENGINE ---
[INFO] Healenium server Port = 7878
[INFO] Healenium server Host = localhost
Mar 14, 2022 3:09:48 PM com.epam.healenium.client.HealingClient makePost
WARNING: Failed to perform POST request. Reason: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:7878
[INFO] sessionKey= null
[WARNING] Couldn't obtain session key from server!
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ SHAFT_ENGINE ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 18 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ SHAFT_ENGINE ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 55 source files to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\target\test-classes
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/testPackage01/appium/IOSBasicInteractionsTest.java: Some input files use or override a deprecated API.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/testPackage01/appium/IOSBasicInteractionsTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/poms/GoogleSearch.java: Some input files use or override a deprecated API that is marked for removal.
[INFO] /C:/Users/Mohab/IdeaProjects/SHAFT_ENGINE/src/test/java/poms/GoogleSearch.java: Recompile with -Xlint:removal for details.
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ SHAFT_ENGINE ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running testPackage01.Test_google
Mar 14, 2022 3:09:57 PM nu.pattern.OpenCV$SharedLoader <init>
SEVERE: OpenCV.loadShared() is not supported in Java >= 12. Falling back to OpenCV.loadLocally().
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initializing Project Structure... @14-03-2022 15:09:58.0991 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initializing Allure Reporting Environment... @14-03-2022 15:09:58.0995 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initializing Extent Reporting Environment... @14-03-2022 15:09:59.0351 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initializing Important Links... @14-03-2022 15:10:00.0848 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initializing Custom Properties... @14-03-2022 15:10:01.0295 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Configuring JDK @14-03-2022 15:10:01.0651 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [GetAbsolutePath] successfully performed. With the following test data [Relative File Path: "generateJdk.bat"]. @14-03-2022 15:10:01.0654 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [WriteToFile] successfully performed. With the following test data [Target File Path: "C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\generateJdk.bat"]. @14-03-2022 15:10:01.0655 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [GetAbsolutePath] successfully performed. With the following test data [Relative File Path: "generateJdk.sh"]. @14-03-2022 15:10:01.0655 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [WriteToFile] successfully performed. With the following test data [Target File Path: "C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\generateJdk.sh"]. @14-03-2022 15:10:01.0711 PM
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Test Data - Excel] @14-03-2022 15:10:04.0247 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [GetAbsolutePath] successfully performed. With the following test data [Relative Folder Path: "target/downloadedFiles/"]. @14-03-2022 15:10:04.0260 PM
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 99.0.4844.51 (resolved driver for Chrome 99)
[main] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Mohab\.cache\selenium\chromedriver\win32\99.0.4844.51\chromedriver.exe
Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 53499

################################################################################################################################################
Detected SHAFT Engine Version: [SHAFT Engine v6.1.20220113]
################################################################################################################################################

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.shaft.tools.io.LogsHelper.setupActivities]
################################################################################################################################################

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[testPackage01.Test_google.beforeClass]
################################################################################################################################################
[ReportManager] Successfully loaded the following test data file [src/test/resources/testDataFiles/testSuite01/TestData.xlsx]. @14-03-2022 15:10:04.0243 PM
[ReportManager] Attempting to run locally on: [Windows-64], [GoogleChrome]. @14-03-2022 15:10:04.0289 PM
[ReportManager] Identifying OS/Driver combination and selecting the correct driver version automatically. Please note that if a new driver executable will be downloaded it may take some time... @14-03-2022 15:10:04.0290 PM
[ReportManager] Successfully Opened Google Chrome. @14-03-2022 15:10:09.0248 PM
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1647263407.918][WARNING]: Ignoring unrecognized log type: client
[1647263407.918][WARNING]: Ignoring unrecognized log type: profiler
[1647263407.918][WARNING]: Ignoring unrecognized log type: server
Mar 14, 2022 3:10:09 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 14, 2022 3:10:09 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 99, so returning the closest version found: 97
Mar 14, 2022 3:10:09 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 99 of 97
[main] INFO com.automation.remarks.video.recorder.monte.MonteRecorder - Recording started
[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: beforeClass] @14-03-2022 15:10:09.0882 PM

################################################################################################################################################
Starting Execution:	[1 out of 3] test cases in the current suite
Test Method:		[testPackage01.Test_google.navigateToURLandVerifyGoogleLogoIsDisplayed]
Test Description:	[TC001 - Navigate to URL and Verify Google Logo is Displayed]
################################################################################################################################################
[ReportManager] Browser Action [NavigateToURL] successfully performed. With the following test data [https://www.google.com/ncr]. @14-03-2022 15:10:15.0397 PM
[ReportManager] Assertion Passed: Then I Assert that the element found by [By.xpath: //*[@id='hplogo' or @alt='Google']] exists. @14-03-2022 15:10:17.0180 PM
[ReportManager] Assertion [ValidateElementExists] PASSED. Expected [Element Should Exist, locator 'By.xpath: //*[@id='hplogo' or @alt='Google']'] and Actual [Element Exists]. Comparison Type [EQUALS]. Validation Type [POSITIVE]. @14-03-2022 15:10:17.0215 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Target URL: [https://www.google.com/ncr], and after redirection: [https://www.google.com] @14-03-2022 15:10:10.0131 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Initial URL: [data:,] @14-03-2022 15:10:10.0261 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [CreateFile] successfully performed. With the following test data [Target Folder: "allure-results//screenshots/20220314-151009", Target File: "\1647263413741_navigateToURLandVerifyGoogleLogoIsDisplayed.gif"]. @14-03-2022 15:10:14.0393 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Screenshot - 1647263416831_navigateToURLandVerifyGoogleLogoIsDisplayed_ValidateElementExists_passed] @14-03-2022 15:10:17.0215 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Animated Gif - navigateToURLandVerifyGoogleLogoIsDisplayed] @14-03-2022 15:10:17.0225 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: navigateToURLandVerifyGoogleLogoIsDisplayed] @14-03-2022 15:10:17.0227 PM

################################################################################################################################################
Starting Execution:	[2 out of 3] test cases in the current suite
Test Method:		[testPackage01.Test_google.searchForQueryandAssertResultsNumDisplayed]
Test Description:	[TC002 - Search for Query and Assert that the number of results is displayed]
################################################################################################################################################
[ReportManager] Element Action [Type] successfully performed. With the following test data [SHAFT_Engine]. @14-03-2022 15:10:19.0337 PM
[ReportManager] Element Action [KeyPress] successfully performed. With the following test data [Enter]. @14-03-2022 15:10:23.0351 PM
[ReportManager] Assertion Passed: Then I Assert that the element found by [By.id: appbar] text does not equal []. @14-03-2022 15:10:26.0498 PM
[ReportManager] Assertion [ValidateElementAttribute] PASSED. Expected [Value Should not be '' for the 'text' attribute, element locator 'By.id: appbar'] and Actual [About 741,000 results (0.47 seconds) ]. Comparison Type [EQUALS]. Validation Type [NEGATIVE]. @14-03-2022 15:10:26.0514 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [CreateFile] successfully performed. With the following test data [Target Folder: "allure-results//screenshots/20220314-151009", Target File: "\1647263418561_searchForQueryandAssertResultsNumDisplayed.gif"]. @14-03-2022 15:10:18.0670 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Element Action [GetText] successfully performed. With the following test data [About 741,000 results (0.47 seconds) ]. @14-03-2022 15:10:24.0530 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Screenshot - 1647263425649_searchForQueryandAssertResultsNumDisplayed_ValidateElementAttribute_passed] @14-03-2022 15:10:26.0512 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Animated Gif - searchForQueryandAssertResultsNumDisplayed] @14-03-2022 15:10:26.0522 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: searchForQueryandAssertResultsNumDisplayed] @14-03-2022 15:10:26.0540 PM

################################################################################################################################################
Starting Execution:	[3 out of 3] test cases in the current suite
Test Method:		[testPackage01.Test_google.clickNextThrice]
Test Description:	[TC003 - Clicks the next button to make sure that the framework can scroll element into view before clicking it]
################################################################################################################################################
[ReportManager] Element Action [Click] successfully performed. With the following test data [Next]. @14-03-2022 15:10:30.0600 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [CreateFile] successfully performed. With the following test data [Target Folder: "allure-results//screenshots/20220314-151009", Target File: "\1647263427364_clickNextThrice.gif"]. @14-03-2022 15:10:27.0478 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Animated Gif - clickNextThrice] @14-03-2022 15:10:30.0605 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: clickNextThrice] @14-03-2022 15:10:30.0613 PM

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[testPackage01.Test_google.afterClass]
################################################################################################################################################
[ReportManager] Successfully Closed All Drivers. @14-03-2022 15:10:44.0522 PM

################################################################################################################################################
Starting Execution of a Configuration (Setup or Teardown) Method
Test Method:		[com.shaft.tools.io.LogsHelper.teardownActivities]
################################################################################################################################################
[ReportManager] Successfully created attachment [SHAFT Engine Logs - Execution log] @14-03-2022 15:10:44.0536 PM

################################################################################################################################################
This test run was powered by SHAFT Engine Version: [SHAFT Engine v6.1.20220113]
SHAFT Engine is licensed under the MIT License: [https://github.com/MohabMohie/SHAFT_ENGINE/blob/master/LICENSE].
################################################################################################################################################
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 49.816 s - in testPackage01.Test_google
[main] INFO com.automation.remarks.video.recorder.monte.MonteRecorder - Recording finished to C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\allure-results\videos\1647263430666_afterClass_recording_2022_14_03_15_10_30.avi
[main] INFO com.automation.remarks.video.RecordingUtils - No jenkinsUrl variable found.
[main] INFO com.automation.remarks.video.RecordingUtils - Video recording: C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\allure-results\videos\1647263430666_afterClass_recording_2022_14_03_15_10_30.avi
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 7 message: <[libx264 @ 00000264515eee40] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 8 message: <[libx264 @ 00000264515eee40] profile High 4:4:4 Predictive, level 4.0, 4:4:4, 8-bit>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 2 Line: 9 message: <[libx264 @ 00000264515eee40] 264 - core 159 - H.264/MPEG-4 AVC codec - Copyleft 2003-2019 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=4 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=24 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00>
[main] INFO ws.schild.jave.ConversionOutputAnalyzer - Unhandled message in step: 3 Line: 33 message: <[mp4 @ 00000264515fd140] Starting second pass: moving the moov atom to the beginning of the file>
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [Video Recording - afterClass] @14-03-2022 15:10:40.0027 PM
[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Current Method log: afterClass] @14-03-2022 15:10:44.0523 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [SHAFT Engine Logs - Execution log: 20220314-151044] @14-03-2022 15:10:44.0538 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [DoesFileExist] successfully performed. With the following test data [File Path: "allure-results/cucumberReport.html"]. @14-03-2022 15:10:44.0538 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [DoesFileExist] successfully performed. With the following test data [File Path: "extent-reports/ExtentReports_14-03-2022_15-09-59-0358-PM.html"]. @14-03-2022 15:10:45.0085 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [GetAbsolutePath] successfully performed. With the following test data [Relative Folder Path: "extent-reports/ExtentReports_14-03-2022_15-09-59-0358-PM.html"]. @14-03-2022 15:10:45.0086 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] File Action [ReadFromFile] successfully performed. With the following test data [File Path: "C:\Users\Mohab\IdeaProjects\SHAFT_ENGINE\extent-reports\ExtentReports_14-03-2022_15-09-59-0358-PM.html"]. @14-03-2022 15:10:45.0175 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Successfully created attachment [HTML - Extent Emailable Execution Report] @14-03-2022 15:10:45.0178 PM
[main] INFO com.shaft.tools.io.ReportManagerHelper - [ReportManager] Attempting to perform the following command locally. Command: [generate_allure_report.bat] @14-03-2022 15:10:45.0181 PM
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- hlm-report-mvn:1.1:buildReport (hlmReportB) @ SHAFT_ENGINE ---
`

### Actual behavior

no tests were executed

### Healenium Web version

3.2.3

### Healenium Backend version

N/A

### Selenium version

N/A

### Platform

Java 17.0.2

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = false
serverHost = localhost
serverPort = 7878
imitatePort = 8000

### Additional context

This is my automation engine:
https://github.com/MohabMohie/SHAFT_ENGINE

**Comment by ElenaStepuro** [comment]
Hello @MohabMohie 
As I can see in maven logs, the test wasn’t started.
Please, recheck your maven configuration in pom.xml file.
Some potential reasons:
Test file not under src/test/java folder
Using <packaging>pom</packaging>
Naming:
By default, the Surefire Plugin will automatically include all test classes with the following wildcard patterns:
·       "**/Test*.java" - includes all of its subdirectories and all Java filenames that start with "Test".
·       "**/*Test.java" - includes all of its subdirectories and all Java filenames that end with "Test".
·       "**/*Tests.java" - includes all of its subdirectories and all Java filenames that end with "Tests".
·       "**/*TestCase.java" - includes all of its subdirectories and all Java filenames that end with "TestCase".

**Comment by MohabMohie** [comment]
@ElenaStepuro please note that -as stated in the bug description- I ran the same command "mvn clean test -Dtest=Test_google" and before upgrading it works, after upgrading it doesn't work.

Please check the attached console for "Expected behavior" as it shows that the same command is working.

**Comment by MohabMohie** [comment]
I can confirm that the issue still exists after upgrading to 3.2.4

So far, 3.2.2 is the last version that's working fine with me so I'm not upgrading my dependency.

But I want to help, so kindly tell me if you need any information from my side.

**Comment by ElenaStepuro** [comment]
Hello @MohabMohie what about healenium-backend? Because as I can see you set it in bug as N/A

**Comment by MandarSakharkar** [comment]
any plans to fix this bug. facing the same issue on 3.3.0 healenium-web. any workaround for this?

**Comment by ujjwala91** [comment]
Hi Team,

I am facing the same issue, any update on this?

**Comment by Alex-Reif** [comment]
Hi @ujjwala91 , @MandarSakharkar please use actual version of Healenium components (hlm-web:3.4.3 and hlm-backend:3.3.4).
Run test, collect logs and attache here
Thanks
