### ISSUE TITLE
[BUG]: Unable run raw selenium scripts showing error in driver = SelfHealingDriver.create(driver1);

### ISSUE THREAD

**Issue by prasathmscss** [healenium/healenium-web#179]
### Describe the bug

@ElenaStepuro 

'm using simple raw selenium code. 

Version using healenium-web-3.2.3

package RawSelenium;

import [org.openqa.selenium.By](http://org.openqa.selenium.by/);
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.epam.healenium.SelfHealingDriver;

public class Google {

public static WebDriver driver;
public static void main(String[] args) {
// TODO Auto-generated method stub

System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"/driver/chromedriver.exe");

WebDriver driver1 = new ChromeDriver();
driver = SelfHealingDriver.create(driver1);   -----> i'm getting in this line
driver.get("https://www.google.com/");
driver.findElement(By.xpath("//a[text()='Gmail']")).click();

}

Starting ChromeDriver 99.0.4844.51 (d537ec02474b5afe23684e7963d538896c63ac77-refs/branch-heads/4844@{#875}) on port 50248
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 14, 2022 7:39:16 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 14, 2022 7:39:17 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 99, so returning the closest version found: 97
Mar 14, 2022 7:39:17 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
INFO: Found CDP implementation for version 99 of 97
Exception in thread "main" java.lang.NoClassDefFoundError: com/typesafe/config/ConfigMergeable
at com.epam.healenium.SelfHealingDriver.create(SelfHealingDriver.java:37)
at RawSelenium.Google.main(Google.java:18)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigMergeable
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)

### How to reproduce the issue

```shell
import [org.openqa.selenium.By](http://org.openqa.selenium.by/);
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.epam.healenium.SelfHealingDriver;

public class Google {

public static WebDriver driver;
public static void main(String[] args) {
// TODO Auto-generated method stub

System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir")+"/driver/chromedriver.exe");

WebDriver driver1 = new ChromeDriver();
driver = SelfHealingDriver.create(driver1);   -----> i'm getting in this line
driver.get("https://www.google.com/");
driver.findElement(By.xpath("//a[text()='Gmail']")).click();

}
```

### Logs appeared during using Healenium

```shell
Docker working fine
```

### Healenium Web version

3.2.3

### Healenium Backend version

3.2.3

### Selenium version

3.141.59

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
serverHost = localhost
serverPort = 7878
imitatePort = 8000

**Comment by Aliaksei-Ashukha** [comment]
Hi @prasathmscss  what com.typesafe.config version do you use in your project?

**Comment by prasathmscss** [comment]
1.4.2 version

**Comment by Aliaksei-Ashukha** [comment]
Could you share your pom.xml? it help us to investigate issue.

**Comment by prasathmscss** [comment]
I'm not using maven package
Raw selenium normal Java project

**Comment by prasathmscss** [comment]
Let's connect in Google meet. i will screen share and explain you

**Comment by prasathmscss** [comment]
[Selenium.zip](https://github.com/healenium/healenium-web/files/8282043/Selenium.zip)
I have upload my java project kindly check from your end
![image](https://user-images.githubusercontent.com/28854326/158752554-acf711a7-c325-48bf-9d39-721f57a9b5a5.png)

**Comment by prasathmscss** [comment]
Really thanks for connecting  with me .. Thanks for your support @Aliaksei-Ashukha
