### ISSUE TITLE
Self healing is not working with Angularjs application

### ISSUE THREAD

**Issue by veeramanikandanvv** [healenium/healenium-web#184]
Version : 3.2.4
Backend version : 3.2.2

We don't see any logs or entry made to the database when working with Angularjs application.

In Eclipse console, we could see exception message as lack of data. No reference locator found when trying to heal.

**Comment by Aliaksei-Ashukha** [comment]
Hi @veeramanikandanvv ,
Message "New element locator have not been found. There is a lack of reference data." means you didn't execute etalon test (success test, without broken locators)

**Comment by veeramanikandanvv** [comment]
Even after running the successful test. I am facing the same problem for
Angularjs application alone.

**Comment by Aliaksei-Ashukha** [comment]
@veeramanikandanvv 
It means somethings was failed. Please provide full necessary bug info asked in template during create bug.

**Comment by veeramanikandanvv** [comment]
I am not seeing any logs or any exceptions while running Angularjs tests.
What are the other information you need?

**Comment by Aliaksei-Ashukha** [comment]
I need logs from hlm-backend container, healenium.properties file.

**Comment by veeramanikandanvv** [comment]
Will share the details

**Comment by Aliaksei-Ashukha** [comment]
@veeramanikandanvv , Will you share the data?

**Comment by veeramanikandanvv** [comment]
Yes, I will.

**Comment by Sathish-vijay** [comment]
@Alex-Reif  could you pls share what is etalon test

**Comment by Alex-Reif** [comment]
Hi @Sathish-vijay , Successful test
At the beginning, we have to run successful tests. Healenium saves a successful locator in the storage to use it as a baseline for the next test executions.
