### ISSUE TITLE
[Need support]: java.lang.ClassCastException: class jdk.proxy2.$Proxy35 cannot be cast to class org.openqa.selenium.TakesScreenshot (jdk.proxy2.$Proxy35 is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.TakesScreenshot is in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by saikrishna446** [healenium/healenium-web#188]
### Describe the problem

integrate our project with healenium getting this error for capturing the sceenshot,

[ERROR] "Login with Valid User"(com.sampleapp.automation.runners.DefaultRunner)  Time elapsed: 53.157 s  <<< FAILURE!
java.lang.ClassCastException: class jdk.proxy2.$Proxy35 cannot be cast to class org.openqa.selenium.TakesScreenshot (jdk.proxy2.$Proxy35 is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.TakesScreenshot is in unnamed module of loader 'app')

### Healenium Web version

3.2.4

### Healenium Backend version

none

### Logs appeared during using Healenium

```shell
[ERROR] "Login with Valid User"(com.sampleapp.automation.runners.DefaultRunner)  Time elapsed: 53.157 s  <<< FAILURE!
java.lang.ClassCastException: class jdk.proxy2.$Proxy35 cannot be cast to class org.openqa.selenium.TakesScreenshot (jdk.proxy2.$Proxy35 is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.TakesScreenshot is in unnamed module of loader 'app')
```

**Comment by saikrishna446** [comment]
I tried this method also "((TakesScreenshot) driver.getDelegate()).getScreenshotAs(OutputType.BYTES);" not locating "getDelefate()" method could u please someone help me?

**Comment by Aliaksei-Ashukha** [comment]
Hi, @saikrishna446 
"getDelefate()" method related to SelfHealingDriver object. If your driver announced as WebDriver, just cast driver to SelfHealingDriver before: 
((TakesScreenshot) ((SelfHealingDriver) driver).getDelegate()).getScreenshotAs(OutputType.BYTES);
