### ISSUE TITLE
[Need support]: http://localhost:7878/ getting Whitelabel Error Page

### ISSUE THREAD

**Issue by mpchethan** [healenium/healenium-web#191]
### Describe the problem
http://localhost:7878/ getting error
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 06 15:25:38 UTC 2022
There was an unexpected error (type=Not Found, status=404).
No message available

### Healenium Web version

3.2.5

### Healenium Backend version

healenium/hlm-backend:3.2.2

### Platform

java

### Logs appeared during using Healenium

```shell
Yes
```

**Comment by chethanmp-agi** [comment]
can you please help on this .

**Comment by Aliaksei-Ashukha** [comment]
Hi @mpchethan , It's not a bug. It's default page of spring project.

**Comment by mpchethan** [comment]
Thanks

**Comment by mpchethan** [comment]
thanks
