### ISSUE TITLE
[BUG]: css locator is not working inside form

### ISSUE THREAD

**Issue by mpchethan** [healenium/healenium-web#195]
### Describe the bug

<form id="headerForm"
        <label id="headerForm

Healenium generated locator is label#headerForm is not working getting error org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified

is it possible get xpath instead of css locator from healenium

### How to reproduce the issue

```shell
<form id="headerForm"
        <label id="headerForm

Healenium generated locator is label#headerForm is not working getting error org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified

is it possible get xpath instead of css locator from healenium
```

### Logs appeared during using Healenium

```shell
org.openqa.selenium.InvalidSelectorException: invalid selector: An invalid or illegal selector was specified
```

### Healenium Web version

3.2.5

### Healenium Backend version

3.2.2

### Selenium version

4.1.2

### Platform

java

### Properties file

recovery-tries=1
score-cap=.6
heal-enabled=true
serverHost = localhost
serverPort = 7878

**Comment by mpchethan** [comment]
Hi Team,

can you please help me.... is there way to generate xpath locator from healenium instead of css because css locators are not working inside form tag

**Comment by ElenaStepuro** [comment]
Hello @mpchethan , what do you mean?

**Comment by mpchethan** [comment]
css locator generated by healenium like label#headerForm is not working inside form tag.. can you please suggestion

**Comment by mpchethan** [comment]
tried manually also css inside form tag is not working

**Comment by mpchethan** [comment]
its in our application only css with id location is not working..

**Comment by Aliaksei-Ashukha** [comment]
Hi @mpchethan , Issue was fixed in the hlm-web 3.3.0

**Comment by mpchethan** [comment]
I will try and let you know and one more query how to generate xpath instead of css 

Thanks

**Comment by Aliaksei-Ashukha** [comment]
@mpchethan , Priority of healed locator type based on client type.
In case you use By.xpath("old"), selector-imitator will try to build new healed element By.xpath as well. ( By.xpath("new") ), otherwise will be use css locator type.

**Comment by mpchethan** [comment]
Ok, thanks.

**Comment by mpchethan** [comment]
Hi ,

 not working
getting error

java.lang.NoSuchMethodError:
org.jsoup.nodes.Document.root()Lorg/jsoup/nodes/Node;
at
com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
at
com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:121)
at
com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:32)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:41)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:49)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:49)
at
com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:58)
at
com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
at com.sun.proxy.$Proxy22.findElement(Unknown Source)
at
org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:70)
at
org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:39)
at com.sun.proxy.$Proxy29.click(Unknown Source)

pure test is passed .

before fixes ..css locator were generating but now error

<dependency>
<groupId>com.epam.healenium</groupId>
<artifactId>healenium-web</artifactId>
<version>3.3.0</version>
</dependency>
Thanks,
Chethan

**Comment by Aliaksei-Ashukha** [comment]
What version of org.jsoup do you use? 
Recomended version 1.11.3

**Comment by mpchethan** [comment]
Ok I will try

**Comment by mpchethan** [comment]
this is old xpath - Failed to find an element using locator By.xpath:
***@***.***='headerForm:prodNewId2']
Healenium generated CSS is findElements {using=css selector,
value=a#headerForm:prodNewId3}]

we need xpath instead of CSS

problem not resolved.

Thanks,
Chethan

**Comment by Aliaksei-Ashukha** [comment]
Hi @mpchethan ,

First off, Healenium doesn't guarantee generate healed locator as xpath.

But there are some rules to increate chance receive xpath locator.

Source client locator:

- be xpath as well.
- shouldn't contains more than one node (ancestor:: , /child, etc).
- starts from "//" character.  

Note: By default healenium generates css selector.

**Comment by mpchethan** [comment]
Thanks
