### ISSUE TITLE
[Need support]: Healnium not healing on elements which are present inside iframe elements.

### ISSUE THREAD

**Issue by raghunadh10** [healenium/healenium-web#204]
Hi Team,

I have taken one test case and ran it successfully for first time . later i have tried healenium by changing web elements in debug mode. the issue is healenium didnt heal that web element . some of the elements got healed and some arent . suprisingly , the elements which are not healed are inside the iframe  element .To ensure this , i have tested nearly 10 xpaths (locators) which are lying inside the iframe . All of them werent healed by healenium. Also i have tested around 20 xpaths which are outside iframe element , they have been healed by healenium succesfully . i wonder if this issue is related to iframe thing.  i am using the latest healenium web and backend too.

### Healenium Web version

3.3.0

### Healenium Backend version

3.2.3

### Selenium version

4.1.1

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000

### Logs appeared during using Healenium

```shell
[main] WARN com.epam.healenium.processor.FindElementProcessor - Failed to find an element using locator By.xpath: //input[@id='sys_display.sn_customerservice_case.account']
Reason: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='sys_display.sn_customerservice_case.account']"}
  (Session info: chrome=104.0.5112.81)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'system12', ip: '0.0.0.0', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [28db31984bfdcec7f5d1eaf543a0a332, findElement {using=xpath, value=//input[@id='sys_display.sn_customerservice_case.account']}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 104.0.5112.81, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: C:\Users\raghunadh10...}, goog:chromeOptions: {debuggerAddress: localhost:57744}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:57744/devtoo..., se:cdpVersion: 104.0.5112.81, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 28db31984bfdcec7f5d1eaf543a0a332
Trying to heal...
[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.
[main] WARN com.epam.healenium.processor.FindElementProcessor - Failed to find an element using locator By.xpath: //input[@id='sys_display.sn_customerservice_case.account']
Reason: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='sys_display.sn_customerservice_case.account']"}
  (Session info: chrome=104.0.5112.81)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'system123', ip: '0.0.0.0', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [28db31984bfdcec7f5d1eaf543a0a332, findElement {using=xpath, value=//input[@id='sys_display.sn_customerservice_case.account']}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 104.0.5112.81, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: C:\Users\raghunadh10...}, goog:chromeOptions: {debuggerAddress: localhost:57744}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:57744/devtoo..., se:cdpVersion: 104.0.5112.81, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 28db31984bfdcec7f5d1eaf543a0a332
Trying to heal...
[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.
[main] WARN com.epam.healenium.processor.FindElementProcessor - Failed to find an element using locator By.xpath: //input[@id='sys_display.sn_customerservice_case.account']
Reason: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@id='sys_display.sn_customerservice_case.account']"}
  (Session info: chrome=104.0.5112.81)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.1', revision: 'e8fcc2cecf'
System info: host: 'Mysystem123', ip: '0.0.0.0', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [28db31984bfdcec7f5d1eaf543a0a332, findElement {using=xpath, value=//input[@id='sys_display.sn_customerservice_case.account']}]
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 104.0.5112.81, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: C:\Users\raghunadh10...}, goog:chromeOptions: {debuggerAddress: localhost:57744}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:57744/devtoo..., se:cdpVersion: 104.0.5112.81, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 28db31984bfdcec7f5d1eaf543a0a332
Trying to heal...
[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.
```

### Additional context
Thank you 
_No response_

**Comment by ElenaStepuro** [comment]
Hello @raghunadh10 , this issue means that example locator wasn't added into db. Please, before run test with healing, run test with correct locators. this is how healenium understands that element should be healed.
You can find explanation in documentation: https://healenium.io/docs

**Comment by raghunadh10** [comment]
Hii @ElenaStepuro  . i have already ran the tests using correct locators for first time . they got stored in db. Whats happening is it isnt healing the elements which are inside the **iframe** . those elements have already stored in db too .i have cross checked them to ensure .  could it be due to iframe thing elena ?   If any inputs are needed , please intimate me

**Comment by Vishnupk1993** [comment]
Hi @ElenaStepuro  even i'm also facing the same issue with Iframe, but for me i cannot see any errors related to **unable to locate the element.** But it's not going inside the iframe

**Comment by Vishnupk1993** [comment]
HI @raghunadh10  @ElenaStepuro @Aliaksei-Ashukha , 

I tried to run a simple script to duplicate the Iframe problem.I wrote a script for Yopmail. And once the mail is received, there will be a clickable link within the iframe. Here are the details about the frame.

![iframe issue](https://user-images.githubusercontent.com/93113082/186110215-5c0874e9-2f46-4a5d-8258-670917b07901.JPG)

I tried to update **id and name** separately from multiple analyzes. And attempted to click the link present in Iframe. The script runs flawlessly. But I can see only the Link related xpath change reflecting in the report that i have updated, the iframe that i updated is not reflecting.
![image](https://user-images.githubusercontent.com/93113082/186110749-22638051-79f6-4ebb-8d13-34bd4048f1cc.png)

Please give me your comments in that regard.

**Comment by raghunadh10** [comment]
Hi @Vishnupk1993  . are you concluding that the link present inside the iframe is getting clicked ?

**Comment by Vishnupk1993** [comment]
@raghunadh10  Yes i'am. IT's getting clicked. But the Frame ID which i updated during debugging is not showing in the console's healed result. And the Healed Report.

**Comment by Vishnupk1993** [comment]
@ElenaStepuro  @raghunadh10  @Aliaksei-Ashukha A small doubt based on the docker. Currently i'm using docker desktop community edition Version 2.0.0.3 . Is it possible to view the locators stored in the backend with the same? or is there any other way through which we can view these ?

**Comment by raghunadh10** [comment]
Hi @Vishnupk1993  . based on your iframe example thing, i understand as follows . you have one xpath for the link inside the iframe .here you arent changing the xpath of the link inside iframe  but you are tyring to change the name and id of the iframe webelement and running the script right . correct me if i wrong .

**Comment by raghunadh10** [comment]
> @ElenaStepuro @raghunadh10 @Aliaksei-Ashukha A small doubt based on the docker. Currently i'm using docker desktop community edition Version 2.0.0.3 . Is it possible to view the locators stored in the backend with the same? or is there any other way through which we can view these ?

I think we can,  by connecting to docker and sql terminal , by running the respective commands we can get access to the locators . but in my case , i am not using docker , i installed them(server, imitator, database)  separately on my local machine . so i am able to see backend data easily using  pgadmin which is a gui for postgre . will try to provide more data  for your case soon.

**Comment by Aliaksei-Ashukha** [comment]
Hi @Vishnupk1993 , 
Yes, you can check stored locators. I recommend use PGAdmin for postgres database.

**Comment by Aliaksei-Ashukha** [comment]
@raghunadh10 , @Vishnupk1993 , could you share project where we can face issues? It helps to investigate problem quickly.

**Comment by ElenaStepuro** [comment]
hi @raghunadh10 application looks at selector table on the full row. Currently we work on url independency

**Comment by raghunadh10** [comment]
Hi @ElenaStepuro  .thank you for your answer. Also can you give me an ETA  when this url independency will be done  because the dynamic url is causing healenium to unable to heal the element . This is an issue right  or is there an temporary alternative solution for this ?

**Comment by Aliaksei-Ashukha** [comment]
Hi @raghunadh10 ,
Solution to support dynamic url was released at hlm-backend 3.2.4
From hlm-backend 3.2.4, client able to adjust build selector key by using KEY_SELECTOR_URL and KEY_SELECTOR_PATH flags.

Example: https://www.google.com/imghp

KEY_SELECTOR_URL - url participates to build  selector key. (https://www.google.by)
KEY_SELECTOR_PATH - path participates to build  selector key. (/imghp)

By default both filled as true.

To fix your issue by 'url independency' please use hlm-backend 3.2.4 and set environment: - KEY_SELECTOR_URL=false

**Comment by Aliaksei-Ashukha** [comment]
Also from hlm-backend 3.2.4 you can check your stored selector via request http://<your healenium server> :7878/healenium/selectors 

For locally: http://localhost:7878/healenium/selectors

**Comment by raghunadh10** [comment]
Hi @Aliaksei-Ashukha  . Thank you for the release . will check on my end and update you  .  can we get the jar file please  as i cannot see it on the releases page of hlm-backend .

**Comment by raghunadh10** [comment]
Hi @Aliaksei-Ashukha  i have build and got jar file using the source code and tried to run . but while running using the above mentioned flag (KEY_SELECTOR_URL) , the issue is still same .healenium is saying there is lack of reference data due to change in url everytime i run the script. do i  need to do anything more than setting the KEY_SELECTOR_URL flag . please check into this 

command --` java -jar hlm-backend-3.2.4.jar --SPRING_POSTGRES_DB=healenium --SPRING_POSTGRES_SCHEMA=healenium --SPRING_POSTGRES_USER=healenium_user --SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K --KEY_SELECTOR_URL=false`

**Comment by Aliaksei-Ashukha** [comment]
Hi @sambeetmohapatra , You don't have to update database, it wont help. 
You should use KEY_SELECTOR_URL=false in hlm-backend container and again run success test to store etalon data to db.
Also you can use /healenium/selectors request to look your stored selectors in the database. And check actual data
Example request: http://localhost:7878/healenium/selectors

**Comment by sambeetmohapatra** [comment]
Hi Aliaksei-Ashukha, Thanks for the response. In our url, there are certain values that keep changing after logging in. And after each login, those values differ from the previous url values. So now, will the KEY_SELECTOR_URL=false in yml file while setting up hlm-backend container suffice ? Also, we are using 3.2.4 hlm-backend version. Please let us know. Thank you

**Comment by Aliaksei-Ashukha** [comment]
There is 2 flags in the hlm-backend container to change the behavior. 
 
- KEY_SELECTOR_URL=true/false
- KEY_SELECTOR_PATH=true/false

 
By default, both have value true. 

Example: http://google.com/images
If you don't want to use even path (/images) you can also turn off it using - KEY_SELECTOR_PATH=false

**Comment by sambeetmohapatra** [comment]
Hi Aliaksei-Ashukha, This seems to be working now. URL is not taken into consideration anymore. Thank you for the help.

**Comment by clrameshchandra** [comment]
Hi Aliaksei-Ashukha, I am trying to set up the Healenium with out docker can you please help me out how to how to disable the url being captured and used for healing. I am using the 3.4.1 hlm-backend version, and 1.3.6 helenium version.
Alos i have updated 

<img width="1792" alt="Screenshot 2023-11-21 at 12 27 39 PM" src="https://github.com/healenium/healenium-web/assets/96456285/025eb636-24af-4aba-b6de-c9f30ab4d9be">

i have start helenium server comment this way.
HLM_SELECTOR_URL=false
HLM_SELECTOR_PATH=false

# Deploy the hlm-backend service
SPRING_POSTGRES_DB=$HLM_POSTGRES_DB SPRING_POSTGRES_SCHEMA=$HLM_POSTGRES_SCHEMA SPRING_POSTGRES_USER=$HLM_POSTGRES_USER SPRING_POSTGRES_PASSWORD=$HLM_POSTGRES_PASSWORD COLLECT_METRICS=$HLM_COLLECT_METRICS SPRING_SERVER_PORT=$HLM_SERVER_PORT HLM_LOG_LEVEL=$HLM_LOG_LEVEL KEY_SELECTOR_URL=$HLM_SELECTOR_URL KEY_SELECTOR_PATH=$HLM_SELECTOR_PATH java -jar hlm-backend.jar 2>&1 & echo $! > ./pid-hlm-backend.file &

But still i see that the url is being captured and used for healing. 
Can you please help me in resolving this ssue.
