### ISSUE TITLE
[BUG]: Class cast Exception

### ISSUE THREAD

**Issue by raghunadh10** [healenium/healenium-web#210]
### Describe the bug

Hi team, 
we have tried to implement healenium in our custom framework for maven project .In this custom framework , we have implemented our own driver class which implements the original WebDriver class . the issue we have come across is , on the method which involves the execute javascript method (executeScript(args))  is not working after converting the normal webdriver to healenium web driver .  The error it is throwing is  " **class cast exception** " 

### How to reproduce the issue

```shell
Example ---

public class customDriver implements WebDriver{
    
    public void createDriver(){	
         
	//creating the driver and sets the webdriver  
}
   public Object executeJS(String script, Object... args) {
		return ((RemoteWebDriver)getDriver()).executeScript(script, args);
	} 

   public void useHealenium() {
		WebDriver healDriver=SelfHealingDriver.create(getCurrentWebDriver());
		drivers.set(getCurrentIndex(),healDriver);
	}
}

customDriver driver = new customDriver() 

driver.createDriver()    //creating one webdriver 
driver.useHealenium()    //calling this method to convert current driver to healdriver
driver.executeJs("console.log("hello"))  //getting class cast exception at this line
```

### Logs appeared during using Healenium

```shell
java.lang.ClassCastException: class jdk.proxy2.$Proxy12 cannot be cast to class org.openqa.selenium.remote.RemoteWebDriver (jdk.proxy2.$Proxy12 
is in module jdk.proxy2 of loader 'app'; org.openqa.selenium.remote.RemoteWebDriver is in unnamed module of loader 'app')
```

### Healenium Web version

3.3.0

### Healenium Backend version

3.2.3

### Selenium version

4.1.1

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000
reportPath=build/reports
screenshotPath=build/screenshots/

**Comment by Aliaksei-Ashukha** [comment]
Hi @raghunadh10 , 
First off, Healenium doesn't handle js scripts (executeScript method), it means there is no healing during call this one. So, if you want to use executeScript method of SelfHealing instance anyway, you should get delegate driver:
((RemoteWebDriver) hlmDriver.getDelegate()).executeScript()

**Comment by raghunadh10** [comment]
Hi @Alex-Reif  . its fine now . thanks for the help .
