### ISSUE TITLE
[Need support]: @DisableHealing annotation, but in python

### ISSUE THREAD

**Issue by ivanpu** [healenium/healenium-web#216]
### Describe the problem

Our tests are written in python using selenium.
We would like to use integrate healenium, but there're few instances where unresolved locators should stay "unhealed".
I see that there's `@DisableHealing` annotation in Java, but we couldn't find anything similar for python.

Is there a way to programmatically mark a python code/function in a similar way to temporary prevent locators healing?

### Healenium Web version

None

### Healenium Backend version

3.2.5 (by using "python example" docker compose)

### Platform

Python

### Logs appeared during using Healenium

```shell
-
```

### Additional context

In tests (which can be executed locally or inside dedicated docker container) we are using "remote webdriver" to connect to the helenium (which runs on a dedicated docker).

**Comment by hwee2173** [comment]
Hi @ivanpu, could you please guide us on how you were able to use the @DisableHealing annotation? We’d like to understand the required setup or configuration to enable this feature in our tests.
