### ISSUE TITLE
[Suggestion]: Caching healings in the Session Context temporarily 

### ISSUE THREAD

**Issue by erikzimmermann** [healenium/healenium-web#227]
### Describe the problem

At the moment, I'm extending a test framework with Healenium. It's great to have Healenium as an open source library for testing. However, there is no way to access all healed elements during the current session. Which is why I opened #224.

In relation to this PR, when I say `access any information about healed items`, I mean that I'd like to have a way of listening to healings that have been performed locally. I know that healed items are already stored in the database and that the session context is not stored, but by using the session as a sort of temporary data holder, we can use it to acknowledge healings that are currently being performed when we don't have any information about the actual locators that were used.

I'd be happy to discuss this further if you have any additional comments. I'd also be happy to make some changes to this PR if necessary.

### Healenium Web version

3.4.2

### Healenium Backend version

3.3.2

### Platform

Java

### Logs appeared during using Healenium

```shell
Unnecessary.
```

**Comment by erikzimmermann** [comment]
Bump.

If my solution should really not be merged in your opinion, it would be amazing if you provide any alternative for accessing healings from a specific session.

**Comment by Alex-Reif** [comment]
Hi @erikzimmermann , thank you interest in Healenium library. But Healenium already provide full list healed elements within selenium session. You can check it , go to http://<hlm-backend>/healenium/report/ .

More information about report you can find here: https://healenium.io/docs/report

**Comment by erikzimmermann** [comment]
Adding following endpoints to the ReportController in the backend would already be sufficient.
```java
    @GetMapping("/data/{uid}")
    public RecordDto getRecord(@PathVariable String uid) {
        return reportService.generate(uid);
    }

    @GetMapping("/data")
    public RecordDto getRecords() {
        return reportService.generate();
    }
```

**Comment by erikzimmermann** [comment]
> Hi @erikzimmermann ,
> 
> We have Healenium Intelij IDEA plugin by which you can update broken selectors.
> 
> Are you sure that it's necessary ? 
> 
> 
> 
> Could you describe case where you need healed data as json?

Sure thing.

I am extending a test framework which uses script files as input to perform actions. Currently, I'm adding support for Healenium to heal elements from those scripts. Since there's a report from that test framework for every executed action, I have to check for healed elements after each step.

Getting the data directly seems to be impossible right now.

Thank you for your quick reply by the way. I really appreciate that!

**Comment by erikzimmermann** [comment]
@Alex-Reif bump

**Comment by Alex-Reif** [comment]
Hi @erikzimmermann , sorry for the delay. Yes, we'll include your api endpoints to the next release next week

**Comment by erikzimmermann** [comment]
@Alex-Reif Hi, any news on this one? :)

**Comment by erikzimmermann** [comment]
@Alex-Reif friendly bump

**Comment by Alex-Reif** [comment]
Hi @erikzimmermann , We added API to hlm-backend you mentioned here https://github.com/healenium/healenium-web/issues/227#issuecomment-1580611900

**Comment by erikzimmermann** [comment]
Thanks a lot! Really appreciate your work!
