### ISSUE TITLE
[Need support]:  Is there any other way from where we can read our healenium properties file

### ISSUE THREAD

**Issue by tarun-rogers** [healenium/healenium-web#232]
### Describe the problem

I am trying to run our automation framework with my healenium infrastructure deployed in kubernetes.

healenium backend, selector imitator and postgresdb are running as pod in kubernetes and they are accessible by below url in our organization network.

**recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://k8.infra.net:7878
hlm.imitator.url = http://k8.infra.net:8000**

but when I run my test it only picks localhost and doesn't pick the urls from properties file. 
I am running the project by java -jar <jar-name> not by mvn clean test

i need to know how can i overcome this.

### Healenium Web version

3.9

### Healenium Backend version

3.3.2

### Properties file

**recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://k8.infra.net:7878
hlm.imitator.url = http://k8.infra.net:8000**

### Logs appeared during using Healenium

```shell
SelfHealingEngine(config=Config(SimpleConfigObject({"awt":{"toolkit":"sun.awt.windows.WToolkit"},"backlight-healing":true,"file":{"encoding":"UTF-8","separator":"\\"},"heal-enabled":true,"hlm":{"imitator":{"url":"http://localhost:8000"},"server":{"url":"http://localhost:7878"}},"intellij":{"debug":{"agent":"true"}},"java":{"awt":{"graphicsenv":"sun.awt.Win32GraphicsEnvironment","printerjob":"sun.awt.windows.WPrinterJob"},
```

**Comment by erikzimmermann** [comment]
Hi, your properties file is probably not in the right directory. You can also submit your properties when instantiating the Healenium driver. At least that's what I did.

**Comment by Alex-Reif** [comment]
Hi @tarun-rogers , Please check location of your healenium.properties file. The right destination: src/test/resources/healenium.properties
