### ISSUE TITLE
self Healing of we element is not happening getting error as "New element locator have not been found. There is a lack of reference data."

### ISSUE THREAD

**Issue by Sathish-vijay** [healenium/healenium-web#238]
### Describe the problem

[main] WARN com.epam.healenium.processor.FindElementProcessor - Failed to find an element using locator By.xpath: //*[@id = 'challenge_locale_ctr']
Reason: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id = 'challenge_locale_ctr']"}
  (Session info: chrome=114.0.5735.199)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ITEM-S133822', ip: '192.168.1.11', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '20.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 114.0.5735.199, chrome: {chromedriverVersion: 114.0.5735.90 (386bc09e8f4f..., userDataDir: C:\WINDOWS\SystemTemp\scope...}, goog:chromeOptions: {debuggerAddress: localhost:54029}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 92d0ec6ddcbff89f87655f3f228f6cc6
*** Element info: {Using=xpath, value=//*[@id = 'challenge_locale_ctr']}
Trying to heal...
[main] WARN com.epam.healenium.processor.HealingProcessor - New element locator have not been found. There is a lack of reference data.

### Healenium Web version

3.2.5

### Healenium Backend version

3.2.5

### Selenium version

3.141

### Platform

Java

### Logs appeared during using Healenium

```shell
2023-07-02 22:43:23 2023-07-02 20:13:23.439  INFO 1 - [7878-exec-4] c.e.h.c.HealingController        : Save locator: By.id(challenge_signin_btn)
```

**Comment by Alex-Reif** [comment]
Hi @Sathish-vijay , description of the issue: https://healenium.io/docs/faq
