### ISSUE TITLE
[Need support]: Does Healenium support react ?

### ISSUE THREAD

**Issue by kherath4139** [healenium/healenium-web#241]
### Describe the problem

Hi I want to confirm if Healenium's Auto Healing is working with UIs built on new front end technologies like React?

### Healenium Web version

3.4.3

### Healenium Backend version

3.3.4

### Selenium version

4.10.0

### Logs appeared during using Healenium

```shell
NA
```

**Comment by Alex-Reif** [comment]
Yes, Healenium is able to work with UIs built on React.
