### ISSUE TITLE
[Need support]: Error while taking screenshot with WebDriver - java.lang.ClassCastException: class com.sun.proxy.$Proxy25 cannot be cast to class org.openqa.selenium.TakesScreenshot (com.sun.proxy.$Proxy25 and org.openqa.selenium.TakesScreenshot are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by ijobs567** [healenium/healenium-web#260]
### Describe the problem

Hello ,
I am facing similar issue
WARN | Trying to heal...
When User enters reference number "ABCDE12345" #
framework.bdd.testcases.UC01Login.user_enters_reference_number(java.lang.String)
java.lang.NoSuchMethodError: 'org.jsoup.nodes.Element org.jsoup.nodes.Document.root()'
at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:25)
at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:144)
at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:35)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63)
at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy44.findElement(Unknown Source)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:68)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy46.click(Unknown Source)

automation.util.SeleniumUtil - This web driver implementation jdk.proxy2.$Proxy44 cannot create screenshots

code I used for screenshot:
public static void takeFullScreenShotForBDD(final SelfHealingDriver driver, final ExtentTest test, String screenshotLog) {
    WebDriver delegatedDriver = driver.getDelegate();

    if (Objects.isNull(driver)) {
        LOG.info("This is NON UI Test Script. Screenshot is not allowed.");
    } else {
        Date d = new Date();
        String fileName = d.toString().replace(" ", "_").replace(":", "_");
        String filePath = fileName + ".png";

        try {

            // Using AShot
            Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(INTEGER_1000))
                    .takeScreenshot(delegatedDriver);

            new File(SCREENSHOTS).mkdir();
            ImageIO.write(screenshot.getImage(), "PNG", new File(SCREENSHOTS + filePath));
            test.info(screenshotLog,
                    MediaEntityBuilder.createScreenCaptureFromPath(SCREENCAPTUREPATH + filePath).build());

        } catch (Exception e) {
            LOG.error(TEST_FAILURE_IOE);
            LOG.error(IO_EXCEPTION + "{}", e);
        }

        try {
            // Using WebDriver's getScreenshotAs
            File scrFile = ((TakesScreenshot) delegatedDriver).getScreenshotAs(OutputType.FILE);
            new File(SCREENSHOTS).mkdir();
            FileUtils.copyFile(scrFile, new File(SCREENSHOTS + filePath));
            test.info(screenshotLog,
                    MediaEntityBuilder.createScreenCaptureFromPath(SCREENCAPTUREPATH + filePath).build());

        } catch (Exception e) {
            LOG.error(TEST_FAILURE_IOE);
            LOG.error(IO_EXCEPTION + "{}", e);
        }
    }
}

### Healenium Web version

3.4.8

### Healenium Backend version

3.4.2

### Selenium version

4.16.1

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.6
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:8000

### Logs appeared during using Healenium

```shell
Note : Its through while execution
```

### Additional context

![image](https://github.com/healenium/healenium-web/assets/41499713/6ba52e79-a64e-4043-bfb3-1b427fbc68cb)

**Comment by ijobs567** [comment]
Earlier I have updated details under -https://github.com/healenium/healenium-web/issues/136

**Comment by Alex-Reif** [comment]
Hi @ijobs567 , you have to update org.jsoup dependancy
