### ISSUE TITLE
[Need support]: Healenium not working as expected

### ISSUE THREAD

**Issue by prakashkp88** [healenium/healenium-web#265]
### Describe the problem

I am trying to use Healenium-Web for my Test Automation I am running through Docker. I am not sure what was the issue, after creating the SelfHealingDriver, I am getting error and test execution not happening. Earlier I was able to successfully run the Healenium Self Healing while using 3.4.6. 

After my system upgrade & STS upgrade, I am facing issues with healenium.

### Healenium Web version

3.4.8

### Healenium Backend version

3.4.4

### Selenium version

4.14.1

### Platform

Java

### Logs appeared during using Healenium

```shell
WARN  healenium.lambda$findAnnotatedInTrace$3 - Failed to check class: <My PageObject Class created by Selenium>
```

### Additional context

below provided Healenium Compose File & my Docker dynamic Grid Compose file.

version: "3"

services:

  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=healenium
      - POSTGRES_USER=healenium_user
      - POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
    networks:
      - healenium

  healenium:
    image: healenium/hlm-backend:3.4.4
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    links:
      - postgres-db
    environment:
      - SPRING_POSTGRES_DB=healenium
      - SPRING_POSTGRES_SCHEMA=healenium
      - SPRING_POSTGRES_USER=healenium_user
      - SPRING_POSTGRES_PASSWORD=YDk2nmNs4s9aCP6K
      - SPRING_POSTGRES_DB_HOST=postgres-db
      - COLLECT_METRICS=true
      - KEY_SELECTOR_URL=false
      - FIND_ELEMENTS_AUTO_HEALING=false
      - HLM_LOG_LEVEL=debug
      
    volumes:
      - ./screenshots/:/screenshots
      - ./logs/:/logs
    networks:
      - healenium

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.4
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - healenium

networks:
  healenium:
    name: healenium
    driver: bridge

Docker Dynamic Grid:
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.17.0-20240123
    volumes:
      - ./assets:/opt/selenium/assets
      - ./config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - 1_admin-hub
    environment:
      - SE_EVENT_BUS_HOST=1_admin-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    networks:
      - healenium  

  1_admin-hub:
    image: selenium/hub:4.17.0-20240123
    ports:
      - "1100:4442"
      - "1101:4443"
      - "1102:4444"
    networks:
      - healenium

networks:
  healenium:
    external: true    

config.toml
[docker]
configs = [
    "selenium/standalone-firefox:4.17.0-20240123", '{"browserName": "firefox"}',
    "selenium/standalone-chrome:4.17.0-20240123", '{"browserName": "chrome"}',
    "selenium/standalone-edge:4.17.0-20240123", '{"browserName": "MicrosoftEdge"}'
    ]

url = "http://127.0.0.1:2375"

video-image = "selenium/video:ffmpeg-6.1-20240123"

**Comment by Alex-Reif** [comment]
Hi @prakashkp88 , Could you attach full logs and collect logs from healenium container. Thanks
