### ISSUE TITLE
[Need support]: 

### ISSUE THREAD

**Issue by sri3690** [healenium/healenium-web#267]
### Describe the problem

how to use the find elements heal in healenium. instead of healing the every single find elements in healenium.

### Healenium Web version

3.2.0

### Healenium Backend version

3.2.5

### Selenium version

3.141.59

### Platform

java11

### Logs appeared during using Healenium

```shell
no logs
```

**Comment by Alex-Reif** [comment]
Hi @sri3690 , By default, Healenium performs healing on all findElement methods executed during the testing session. However, healing is not performed when using findElements methods. If you want to enable healing for findElements, you can set FIND_ELEMENTS_AUTO_HEALING variable of healenium-backend service or by toggling the relevant selector on the Healenium selectors page.
