### ISSUE TITLE
[BUG]:  java.lang.NoSuchMethodError: 'org.jsoup.nodes.Document org.jsoup.nodes.Document.normalise()

### ISSUE THREAD

**Issue by QACodeDev** [healenium/healenium-web#280]
### Describe the bug

I am getting exception when trying to execute below lines and i am getting exception at line 2

		line1-	WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(timeout));
		line 2-	wait.until(ExpectedConditions.invisibilityOfElementLocated(ByLocator(locator)));

i am using latest jsoup  and tried with 1.15.3 and 1.17.2

 <dependency>
    	<groupId>org.jsoup</groupId>
	    <artifactId>jsoup</artifactId>
	    <version>1.18.1</version>
	</dependency>

### How to reproduce the issue

```shell
Run the code with below lines:

WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(timeout));
wait.until(ExpectedConditions.invisibilityOfElementLocated(ByLocator(locator)));
```

### Logs appeared during using Healenium

```shell
java.lang.NoSuchMethodError: 'org.jsoup.nodes.Document org.jsoup.nodes.Document.normalise()'
	at com.epam.healenium.treecomparing.JsoupHTMLParser.parse(JsoupHTMLParser.java:24)
	at com.epam.healenium.SelfHealingEngine.parseTree(SelfHealingEngine.java:140)
	at com.epam.healenium.processor.HealingProcessor.execute(HealingProcessor.java:35)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:42)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.processor.BaseProcessor.process(BaseProcessor.java:50)
	at com.epam.healenium.handlers.proxy.BaseHandler.findElement(BaseHandler.java:63)
	at com.epam.healenium.handlers.proxy.SelfHealingProxyInvocationHandler.invoke(SelfHealingProxyInvocationHandler.java:39)
	at jdk.proxy2/jdk.proxy2.$Proxy24.findElement(Unknown Source)
	at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:569)
	at org.openqa.selenium.support.ui.ExpectedConditions$20.apply(ExpectedConditions.java:565)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:203)
```

### Expected behavior

It should work with wait.until(ExpectedConditions.invisibilityOfElementLocated(ByLocator(locator)));

### Actual behavior

throwing exception java.lang.NoSuchMethodError: 'org.jsoup.nodes.Document org.jsoup.nodes.Document.normalise()'

### Healenium Web version

3.5.2

### Healenium Backend version

3.4.5

### Selenium version

4.22.0

### Platform

Java

### Properties file

recovery-tries = 1
score-cap = 0.5
heal-enabled = true
hlm.server.url = http://localhost:7878
hlm.imitator.url = http://localhost:9000

### Additional context

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.qanovation</groupId>
  <artifactId>QAN_Test_Maven</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>QAN_Test_Maven</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <aspectj.version>1.9.6</aspectj.version>
    <selenium-version>4.22.0</selenium-version>
    <testng-version>6.14.3</testng-version>
    <allure-testng-version>2.13.9</allure-testng-version>
    <log4j-version>2.14.1</log4j-version>
    <extentreports-version>2.41.2</extentreports-version>
    <rest-assured>4.5.1</rest-assured>
    <mssql-jdbc>9.4.0.jre16</mssql-jdbc>
    <apache-poi>3.13</apache-poi>
   	<microsoft-azure>1.11.3</microsoft-azure>
    <org-json>20230227</org-json>
    <maven-complier>3.5.1</maven-complier>
    <maven-surefire-plugin-version>3.0.0-M3</maven-surefire-plugin-version>
    <hlm.report.mvn.version>1.1</hlm.report.mvn.version>
    <healenium.version>3.5.2</healenium.version>
  </properties>
  	<description>To execute tests in parallel using testNG and selenium grid 4</description>
  	 <pluginRepositories>
        <pluginRepository>
            <id>bintray-healenium</id>
            <url>http://dl.bintray.com/epam/healenium</url>
        </pluginRepository>
    </pluginRepositories>
  <build>
  <pluginManagement>
   <plugins>
	   <plugin>
         <groupId>com.epam.healenium</groupId>
         <artifactId>hlm-report-mvn</artifactId>
         <version>1.1</version>
         <executions>
           <execution>
             <id>hlmReport</id>
             <phase>compile</phase>
             <goals>
               <goal>initReport</goal>
             </goals>
           </execution>
           <execution>
             <id>hlmReportB</id>
             <phase>test</phase>
             <goals>
               <goal>buildReport</goal>
             </goals>
           </execution>
         </executions>
       </plugin>
      <plugin>
	      <groupId>org.apache.maven.plugins</groupId>
	        <artifactId>maven-compiler-plugin</artifactId>
	        <version>${maven-complier}</version>
	        <configuration>
	          <source>1.8</source>          
	          <target>1.8</target>
	          <encoding>UTF-8</encoding>     
	        </configuration>
	      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven-surefire-plugin-version}</version>
        <configuration>
        <testFailureIgnore>true</testFailureIgnore>
          <suiteXmlFiles>
            <suiteXmlFile>testng-execution-engine.xml</suiteXmlFile>             
          </suiteXmlFiles>
           <argLine>
                    -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
            </argLine>
        </configuration>
        <dependencies>
            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>
        </dependencies>
      </plugin>
    </plugins>
   </pluginManagement>
  </build>  
  <dependencies>  
  	<dependency>
	    <groupId>org.testng</groupId>
	    <artifactId>testng</artifactId>
	    <version>${testng-version}</version>
	    <scope>compile</scope>
	</dependency>     	  
 	 <dependency>
	    <groupId>org.seleniumhq.selenium</groupId>
	    <artifactId>selenium-java</artifactId>
	    <version>${selenium-version}</version>
	</dependency>
	<dependency>
		<groupId>log4j</groupId>
		<artifactId>log4j</artifactId>
		<version>1.2.16</version>
	</dependency>
	 <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j-version}</version>
     </dependency>
     <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j-version}</version>
            <scope>provided</scope>
     </dependency>
	 <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure-testng-version}</version>
    </dependency>
	<dependency>
	    <groupId>com.relevantcodes</groupId>
	    <artifactId>extentreports</artifactId>
	    <version>${extentreports-version}</version>
	</dependency>	
	<dependency>
		<groupId>org.seleniumhq.selenium</groupId>
		<artifactId>selenium-htmlunit-driver</artifactId>
		<version>2.52.0</version>
	</dependency>
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-io</artifactId>
	    <version>1.3.2</version>
	</dependency>	
	<dependency>
	    <groupId>com.googlecode.json-simple</groupId>
	    <artifactId>json-simple</artifactId>
	    <version>1.1.1</version>
	</dependency>	
	<dependency>
	    <groupId>commons-io</groupId>
	    <artifactId>commons-io</artifactId>
	    <version>2.7</version>
	</dependency>
	<dependency>
		<groupId>org.apache.poi</groupId>
		<artifactId>poi-ooxml</artifactId>
		<version>${apache-poi}</version>
	</dependency>
	<dependency>
	    <groupId>io.rest-assured</groupId>
	    <artifactId>rest-assured</artifactId>
	    <version>${rest-assured}</version>		    
	</dependency>
	<dependency>
	   <groupId>org.json</groupId>
	    <artifactId>json</artifactId>
	    <version>${org-json}</version>
	</dependency>
	<dependency>
    	<groupId>com.microsoft.sqlserver</groupId>
	    <artifactId>mssql-jdbc</artifactId>
	    <version>${mssql-jdbc}</version>
	</dependency>
	<dependency>
	<groupId>com.microsoft.azure</groupId> 
		<artifactId>msal4j</artifactId> 
		<version>${microsoft-azure}</version> 
	</dependency>
	 <dependency>
        <groupId>com.epam.healenium</groupId>
        <artifactId>healenium-web</artifactId>
        <version>${healenium.version}</version>
    </dependency>    
    <dependency>
    	<groupId>org.jsoup</groupId>
	    <artifactId>jsoup</artifactId>
	    <version>1.18.1</version>
	</dependency>
  </dependencies> 
</project>

**Comment by Alex-Reif** [comment]
Fixed at 3.5.3
