### ISSUE TITLE
It is not working if tag name changes like from div to span something like that

### ISSUE THREAD

**Issue by prasanna532** [healenium/healenium-web#37]
I tried to heal for google searchbox with changing name attribute and Tag name also but it is finding the other input Tags

Using healed locator: By.cssSelector: center > input.gNO89b[data-ved="0ahUKEwjpzKujgN3nAhVOy4sBHb3ZD5gQ4dUDCAY"][name="btnK"][type="submit"][value="Google Search"][aria-label="Google Search"]
Other choice: By.cssSelector: html
Other choice: By.cssSelector: div.tfB0Bf > center:nth-child(2)

**Comment by GannaChernyshova** [comment]
@prasanna532 Was healing performed successfully with By.cssSelector: center > input.gNO89b[data-ved="0ahUKEwjpzKujgN3nAhVOy4sBHb3ZD5gQ4dUDCAY"][name="btnK"][type="submit"] ?
Other choice in console log is expected behavior. Healenium generates 3 possible locators and use only the first, most reliable one, for healing

**Comment by prasanna532** [comment]
@GannaChernyshova  Healing is not successful when the tag name also changes yes i changed recovery tries to 5 also but it not able to find.
Iam trying to find the (google) text box which has tag name **input** i have changed input tag to **div** then it is finding the submit button instead of google text box.

Note: it is working when any attribute changes. Only iam observed the issue when there is change in the tag also.

**Comment by GannaChernyshova** [comment]
@prasanna532 Healenium needs to have first successful test run. It will store successful locator and in case of control changes on UI Healenium will go to the storage, get successful locator, compare to current page source and generate new 'healed' locator. If you have faced with cases when healing did not work please provide some hard data so we could solve your issue
