### ISSUE TITLE
Relative elements search works as a global search

### ISSUE THREAD

**Issue by sobkoNick** [healenium/healenium-web#43]
There is a case when a user wants to find an element within some parent element then this search is working as a global search, not based on the parent element.

For example, 
-using selenide:
`$(By.xpath("parent locator")).find(By.xpath("relative to parent locator"))`
or with selenium:
`webDriverUtils.getDriver().findElement(By.xpath("parent locator")).findElement(By.xpath("relative to parent locator"))`
both actually work as:
`webDriverUtils.getDriver().findElement(By.xpath("relative to parent locator"))`.

**My environment properties:**
        <cucumber.version>4.7.1</cucumber.version>
        <selenium.version>3.141.59</selenium.version>
        <selenide.version>5.3.1</selenide.version>
        <webdrivermanager.version>3.7.1</webdrivermanager.version>
        <healenium.version>2.0.4.1</healenium.version>
Gooogle Chrome Version 80.0.3987.132 (Official Build) (64-bit).

**Comment by GannaChernyshova** [comment]
should save context in findElement to proxy it
