### ISSUE TITLE
Please provide valid test methods for different frameworks

### ISSUE THREAD

**Issue by nareshm1** [healenium/healenium-web#61]
Hi @GannaChernyshova @LittleDecorator @DzmitryHumianiuk @KozhevnikovSergey @OleksiiYevsovych

Hope you are all good !!

Appreciate guyzzz.. Your are awesome as whole world is running behind the payable frameworks you are providing frameworks as open source

I am trying healenium 3.0 new version which I am running with TestNG framework .
With No command line I was able to run the test suite(directly from eclipse) and can heal the locators but unable to generate report through this way and while running with mvn clean test on command line due to compiler mvn compiler error because version 1.8 is giving an error .

Could you please bring more information on the healenium 3.0.5 with TestNG and steps to generate report widely.
Steps follows : 
1. Create Testng.xml instead of gradle 
2. Right click on it --> Run As  --> TestNG suite
3. Programs runs and heals
**4. But where these healed locators are save and where to check them ?
5. If reports are generated where are these displayed? paths?**

**If provided with various others frameworks also that helps!!**

Thanks in Advance!!
Naresh .

This could be helpful
Link to github : https://github.com/nareshm1/Self_healing_automation.git

**Comment by Aliaksei-Ashukha** [comment]
Discussion was moved to https://github.com/healenium/healenium-web/issues/63
