### ISSUE TITLE
Continuous ppst with error on Testng suite eith morr information 

### ISSUE THREAD

**Issue by nareshm1** [healenium/healenium-web#63]
Hi @GannaChernyshova @LittleDecorator @DzmitryHumianiuk @KozhevnikovSergey @OleksiiYevsovych

Hope you are all good !!

Appreciate guyzzz.. Your are awesome as whole world is running behind the payable frameworks you are providing frameworks as open source

I am trying healenium 3.0 new version which I am running with TestNG framework .
With No command line I was able to run the test suite(directly from eclipse) and can heal the locators but unable to generate report through this way and while running with mvn clean test on command line due to compiler mvn compiler error because version 1.8 is giving an error .

Could you please bring more information on the healenium 3.0.5 with TestNG and steps to generate report widely.
Steps follows : 
1. Create Testng.xml instead of gradle 
2. Right click on it --> Run As  --> TestNG suite
3. Programs runs and heals
**4. But where these healed locators are save and where to check them ?
5. If reports are generated where are these displayed? paths?**

**If provided with various others frameworks also that helps!!**

Thanks in Advance!!
Naresh .

This could be helpful
Link to github : https://github.com/nareshm1/Self_healing_automation.git

**Comment by GannaChernyshova** [comment]
Hi Naresh! 
We support report generation only for Maven or Gradle test runs. Healenium do not trigger report generation for test runs from TestNG or Junit

**Comment by nareshm1** [comment]
Hi Anna,

Thanks for writing !!

I have run through Maven as well but I was unable to generate the report .
1. Docker is up
[image: image.png]
2. Maven is updated
3. executed *mvn clean test*
4.
[image: image.png]
5. Program up and running ..
6. But at report it giving some error as below :


[image: image.png]
[image: image.png]

helanium properties file is :
[image: image.png]

My docker is :
[image: image.png]

Thanks,
Naresh

**Comment by Aliaksei-Ashukha** [comment]
Hi nareshm1 , could you attach screenshots again?

**Comment by nareshm1** [comment]
Hi @Aliaksei-Ashukha @GannaChernyshova 


I have run through Maven as well but I was unable to generate the report .
1. Docker is up
![image](https://user-images.githubusercontent.com/67036539/93571270-d5d11b00-f9b1-11ea-91aa-ef07513e215e.png)
2. src/test/resources  - **docker-compose up -d**
![image](https://user-images.githubusercontent.com/67036539/93571422-0913aa00-f9b2-11ea-8d4d-0ac6706cc056.png)
3. Run **mvn clean test**
![image](https://user-images.githubusercontent.com/67036539/93571513-32ccd100-f9b2-11ea-90d8-607a8cc3f15c.png)
4. Maven is up and running
5. An error while invoking hlm report 
![image](https://user-images.githubusercontent.com/67036539/93571634-5bed6180-f9b2-11ea-8920-72828432bc7b.png)
6. Test completed and healed the locators
7. Error in report generation
![image](https://user-images.githubusercontent.com/67036539/93571896-b686bd80-f9b2-11ea-8880-61f44d0ec3bf.png)


healenium .prop file : 
![image](https://user-images.githubusercontent.com/67036539/93571970-cf8f6e80-f9b2-11ea-9098-02f52ce9eda5.png)

My docker  : 
![image](https://user-images.githubusercontent.com/67036539/93572030-e5049880-f9b2-11ea-9da4-e6bf8eaa6413.png)

Thanks,
Naresh

**Comment by Aliaksei-Ashukha** [comment]
Try to use localhost instead of 192.168.99.100 in configuration

**Comment by nareshm1** [comment]
@Aliaksei-Ashukha  
Tried with localhost instead of 192.168.99.100 in config

Getting below error : 
![image](https://user-images.githubusercontent.com/67036539/93574267-d8357400-f9b5-11ea-89f5-d08971db0820.png)

![image](https://user-images.githubusercontent.com/67036539/93574340-ed120780-f9b5-11ea-8c01-57fd8c44e0bb.png)

![image](https://user-images.githubusercontent.com/67036539/93574406-fe5b1400-f9b5-11ea-9e8b-76eaf5704d5b.png)
![image](https://user-images.githubusercontent.com/67036539/93574455-10d54d80-f9b6-11ea-9ef5-9e0d180d62da.png)

**Comment by nareshm1** [comment]
@GannaChernyshova @Aliaksei-Ashukha  

git hub  : https://github.com/nareshm1/Self_healing_automation.git

**Comment by Aliaksei-Ashukha** [comment]
Hi @nareshm1, 
1. change in healenium.properties: localhost instead of 192.168.99.100 
2. get .html pages from local directory in Base.class.
for example: driver.get("file:///C:/projects/Self_healing_automation/src/main/java/Webpages/html/bootstrap1.html#");
3. use correct xpath in Page1.class :  "//*[@id='validationCustom01']"  instead of    "//label[contains(.,'First name')]/../input"

**Comment by nareshm1** [comment]
Hi @Aliaksei-Ashukha 

I have made changes as mentioned but still same error response

**Comment by Aliaksei-Ashukha** [comment]
Hi @nareshm1,

Please check on 3.0.7 version of healenium/hlm-backend service.

**Comment by nareshm1** [comment]
Thanks @Aliaksei-Ashukha @GannaChernyshova 
have a look on new issue for 3.0.7 and 3.0.2 https://github.com/healenium/healenium-report-mvn/issues/3#issue-749174291
