### ISSUE TITLE
healenium-web doesn't support IE browser.

### ISSUE THREAD

**Issue by skptricks** [healenium/healenium-web#71]
healenium-web doesn't support IE browser. Could you please update.

**Comment by Aliaksei-Ashukha** [comment]
Hi @skptricks,
Could you provide error ?

Notes:
Setup IE web-driver:

        WebDriverManager.edgedriver().setup();
        EdgeOptions options = new EdgeOptions();
        //declare delegate
        WebDriver delegate = new EdgeDriver(options);
        //create self-healing driver
        driver = SelfHealingDriver.create(delegate);

**Comment by GannaChernyshova** [comment]
Tested locally, no issues found
