### ISSUE TITLE
setFileDetector() not working with SelfHealingDriver

### ISSUE THREAD

**Issue by jeevanreddy58** [healenium/healenium-web#72]
typecast from SelfHealingDriver to RemoteWebDriver is not working when used with setFileDetector method.

java.lang.ClassCastException: com.sun.proxy.$Proxy31 cannot be cast to org.openqa.selenium.remote.RemoteWebDriver

code :
                options = getChromeOptions();
                options.setCapability("enableVNC", enableVNC);    
                driver = SelfHealingDriver.create(new RemoteWebDriver(new URL(gridHubURL), options));
                ((RemoteWebDriver) driver).setFileDetector(new LocalFileDetector());

**Comment by GannaChernyshova** [comment]
Hi @jeevanreddy58, thank you for an issue, we'll take look and provide the fix.

**Comment by Truculent1997** [comment]
Is there any update on this? @GannaChernyshova

**Comment by GannaChernyshova** [comment]
Hi @Truculent1997 
can you please try this construction:
((RemoteWebDriver) driver.getDelegate()).setFileDetector(new LocalFileDetector())

**Comment by Truculent1997** [comment]
Thanks @GannaChernyshova
