### ISSUE TITLE
Doesnt produce Healenium report if there is any single test failure in the entire execution.

### ISSUE THREAD

**Issue by bhargavkumar-65** [healenium/healenium-web#75]
Below are the expected Messages in console for every execution, but whenever there is any single test failure then report is not being generated at all [may be it is generating but we do not see Info messages like below in the case of failures]
[INFO] --- hlm-report-mvn:1.1:buildReport (hlmReportB) @ Healenium ---
Mar 11, 2021 4:55:36 PM com.epam.healenium.client.HealingClient makePost
INFO: External service call completes with success: healenium/report/cac17a5f-86d5-41fe-8af9-0f062697572d
[INFO] Report available at http://localhost:7878/healenium/report/cac17a5f-86d5-41fe-8af9-0f062697572d

here is my repo. https://github.com/AutoInfra/HealeniumTestng
can reproduce the issue via enabling amazon test in suites/testng.xml

**Comment by GannaChernyshova** [comment]
Hi @bhargavkumar-65,
there is a workaround to fix this issue. 
For maven add next lines to maven-surefire-plugin in pom.xml: 
<configuration>
       <testFailureIgnore>true</testFailureIgnore>
</configuration> 
For gradle add next line into test configuration in build.gradle:
ignoreFailures =true

**Comment by bhargavkumar-65** [comment]
@GannaChernyshova it works, thanks so much.
