### ISSUE TITLE
PageAwareBy not working

### ISSUE THREAD

**Issue by kavin30** [healenium/healenium-web#79]
Hi the class name, method names etc.The information related to element which are passed to database couldn't be assigned in custom manner.I tried using pageAwareBy but it is not working.

**Comment by suryapaandeeswaran** [comment]
HI Team, PFB for the example scenario. The information related to element which are passed to database couldn't be assigned in custom manner and its automatically taking the current class and package where the driver.findElement is getting executed. Hence PageAwareBy is not working. 

I'm expecting AjaxLoadPage in the class name column of database but getting NewTest as a className in database.

**Java Selenium Code:**
package selenium;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import com.epam.healenium.PageAwareBy;

import pages.AjaxLoadPage;

public class NewTest extends BaseTest {

    
    @Test
    public void testButtonClickWithFindByAnnotationPageOne() {
        driver.get("https://sha-test-app.herokuapp.com/");
        By locator = PageAwareBy.by("AjaxLoadPage",By.id("markup-generation-button"));
        driver.findElement(locator).click();
        
    }
}


**Attached the database reference:**
<img width="1437" alt="Screen Shot 2021-04-12 at 4 39 49 pm" src="https://user-images.githubusercontent.com/32605723/114351318-c6175f00-9bad-11eb-8e77-0ad53f966e2e.png">

**Comment by GannaChernyshova** [comment]
Hi @kavin30 
try to use Healenium-web version 3.0.3-beta-2 and simply locate your element By locator = By.id("markup-generation-button")
PageAwareBy is for healenium-web 2 and lower

**Comment by kavin30** [comment]
@GannaChernyshova - Is there any option to assign the method name or class name by me for an element?

**Comment by suryapaandeeswaran** [comment]
@GannaChernyshova - So PageAwareBy is deprecated in the latest version ?

**Comment by GannaChernyshova** [comment]
@kavin30 @suryapaandeeswaran yes, PageAwareBy is deprecated. Method name and class name assigns automatically since version 3.0
