### ISSUE TITLE
403 when building with gradel

### ISSUE THREAD

**Issue by zedgell** [healenium/healenium-web#92]
I am getting a 403 when building with gradle.
`Could not GET 'https://dl.bintray.com/epam/healenium/com/epam/healenium/healenium-web/3.0.2/healenium-web-3.0.2.pom'. Received status code 403 from server: Forbidden`

**Comment by GannaChernyshova** [comment]
Hi @zedgell 
we migrated from Bintray to Maven so please use latest version 3.1 or 3.0.3-beta-8
https://mvnrepository.com/artifact/com.epam.healenium/healenium-web
