### ISSUE TITLE
Healing is not working for real DOM change

### ISSUE THREAD

**Issue by bhuvana-m** [healenium/healenium-web#94]
Hi @DzmitryHumianiuk ,
Healing is not working even there is a DOM level change in the application also the healenium-example project is not healing for the sample site .Getting New element have not been found " exception 
Logs for reference:

2021-04-28 15:51:08.833  WARN 1 - [7878-exec-5] .DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.util.ArrayList<com.epam.healenium.treecomparing.Node>` out of START_OBJECT token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<com.epam.healenium.treecomparing.Node>` out of START_OBJECT token\n  at [Source: (PushbackInputStream); line: 1, column: 163] (through reference chain: com.epam.healenium.model.dto.SelectorRequestDto["nodePath"]->java.util.ArrayList[0])]

Thanks ,
Bhuvana

**Comment by DzmitryHumianiuk** [comment]
@GannaChernyshova ^

**Comment by GannaChernyshova** [comment]
Hi @bhuvana-m! What version of Healenium are you using?

**Comment by bhuvana-m** [comment]
Hi @GannaChernyshova ,
Tried both  3.0.2 and 3.0
3 beta version .
I have cloned the healenium-example-maven project from the github repo and tried to execute the markuptest class but the same error displayed

**Comment by GannaChernyshova** [comment]
Is hlm-backend is up and running?

**Comment by bhuvana-m** [comment]
Yes it running Anna.
Both hlm backend and db is running

**Comment by alexis9205110** [comment]
Hi. I have the same error. I think that the tree-comparing-0.4.8 jar is corrupted. 

![image](https://user-images.githubusercontent.com/83432822/116762984-c901b480-a9e1-11eb-905d-d571dba5c81e.png)

**Comment by bhuvana-m** [comment]
Hi @alexis9205110 ,
Yes Alexis,even I feel the same.
@GannaChernyshova ,
Please provide solution for the above issue

**Comment by GannaChernyshova** [comment]
Hi @bhuvana-m, @alexis9205110 
we are working on artefacts migration from JCenter bintray to Maven Central because JCenter is going to the sunset. In few days issues with dependencies will be fixed

**Comment by Aliaksei-Ashukha** [comment]
Hi @bhuvana-m, Would you write me in Skype please, and we'll discuss more detail there.
My Skype: live:9e28d39b52d0dafd

**Comment by bhuvana-m** [comment]
Thanks for the update @GannaChernyshova 
Sure will connect @alexis9205110

**Comment by bhuvana-m** [comment]
@alexis9205110 
@GannaChernyshova 
Do we have any temporary solution for  this issue

**Comment by GannaChernyshova** [comment]
Hi @alexis9205110 @bhuvana-m 
please try the latest version healenium-web:3.0.3-beta-8

**Comment by GannaChernyshova** [comment]
@alexis9205110 @bhuvana-m Hi! 
Have you solved the issue with new version?

**Comment by bhuvana-m** [comment]
Hi @GannaChernyshova ,
The healing is working when using direct findelement method  but its not working  when elementTobeclickable() or other expectedcondotiona methods used.it's getting failed to find the healed locator 

Ex:invisibiliyyofElementLocated(final by locator)

**Comment by GannaChernyshova** [comment]
Hi @bhuvana-m 
To verify invisibility of element to should use @DisableHealing annotation on the method. If element is not present in DOM Healenium can't heal it.
Also could you please provide an example of your code with elementTobeclickable()? We checked on our side and everything works fine to this kind of expected conditions.
