### ISSUE TITLE
java.lang.ClassNotFoundException: com.epam.healenium.treecomparing.NodeDistance

### ISSUE THREAD

**Issue by shukhov88** [healenium/healenium-web#95]
The only Healenium version I was able to fetch by Maven or Gradle is '3.0.3-beta-7' (looks like all the other versions available in repository lack source code in the package).
I used example repos to try out Healenium: [Gradle example](https://github.com/healenium/healenium-example) and [Maven example](https://github.com/healenium/healenium-example-maven)
Both the repos fail to run tests with the error: 
java.lang.NoClassDefFoundError: com/epam/healenium/treecomparing/NodeDistance

**Comment by GannaChernyshova** [comment]
Hi @shukhov88 
please try the latest version healenium-web:3.0.3-beta-8

**Comment by shukhov88** [comment]
Hi @GannaChernyshova , thanks for the answer.
Where can I find 3.0.3-beta-8 ?

**Comment by GannaChernyshova** [comment]
@shukhov88 It's not displayed there yet but already published. Just try to update the version in dependencies

**Comment by shukhov88** [comment]
@GannaChernyshova tried, it says "Dependency 'com.epam.healenium:healenium-web:3.0.3-beta-8' not found".
I'll give it a try later, thanks.
